### ISSUE TITLE
Research refresh functionality

### ISSUE THREAD

**Issue by lauren-li** [zowe/zowe-explorer-vscode#1048]
The purpose of this issue is to track research on refresh in Zowe Explorer.
- Gather issues related to refresh in Zowe Explorer
- Examine the different types of refresh in Zowe Explorer
- Outside-in view/use case scenarios
- Look for areas of improvement

**issues related to refresh in Zowe Explorer**
*Issues that are directly refresh*
- https://github.com/zowe/vscode-extension-for-zowe/issues/1021 Refresh button not working (for Favorites)
- https://github.com/zowe/vscode-extension-for-zowe/issues/754 Requests sent to z/OS when tree item is closed
- ~#1078 Tree Refresh button does not pick up extenders' profile updates~

*Issues that are functions calling on refresh*
(These filepaths are based on the current `monorepo-switch` branch.
- Profiles:
  - https://github.com/zowe/vscode-extension-for-zowe/issues/1033 Clear all settings and default profile in meta yaml to null if profiles are manually deleted(?)
  - https://github.com/zowe/vscode-extension-for-zowe/issues/752 Refresh required for profile created in Zowe CLI to be available in ZE
- Data Sets:
  - https://github.com/zowe/vscode-extension-for-zowe/issues/843 Refresh DS after Migrate/Recall DS 
- USS: 
  - https://github.com/zowe/vscode-extension-for-zowe/issues/769 Refresh USS file list under directory
  - https://github.com/zowe/vscode-extension-for-zowe/issues/650 USS tree collapses after folder rename
  - #1079 When using Toggle Binary/Text command, only refresh parent node
- Jobs:
  - https://github.com/zowe/vscode-extension-for-zowe/issues/988 Enable update of Job Logs
  - https://github.com/zowe/vscode-extension-for-zowe/issues/578 Call refresh on Jobs view when a job is deleted

*Issues I'm not sure about* (i.e. Cannot recreate issue or unsure if it is still an issue)
- https://github.com/zowe/vscode-extension-for-zowe/issues/755 eTag error encountered when saving file in root of USS tree
- https://github.com/zowe/vscode-extension-for-zowe/issues/471 Refresh of DS is taking long time
- https://github.com/zowe/vscode-extension-for-zowe/issues/832 Refresh DS members without having to individually select them

**Different types of refresh in Zowe Explorer**
*In the `zowe-explorer-api` package*
- ~~src/Utils.ts:~~ (This file no longer exists.)
  - ~~`refreshTree(IZoweTreeNode)`: Refresh profile and session (sessNode, which is type IZoweTreeNode)~~
- src/ProfilesCache.ts:
  - `refresh(apiRegister: ZoweExplorerApi.IApiRegisterClient)`:
    - Gets base profiles
    - Gets extender profiles
    - Get an array of all profiles (Profiles.allProfiles)
    - Get an array of all profile types (Profiles.allTypes)
    - Remove all profiles from profilesForValidation array (profiles.profilesForValidation)
- src/IZoweTree.ts (Declarations only):
  - `refresh()`: Refreshes Tree
  - `refreshElement(node: IZoweNodeType)`: Refreshes tree element, i.e. a tree node
  - `refreshPS(node: IZoweNodeType)`: Refreshes the passed node with current mainframe data. Seems to be used (defined) by the Data Sets view only (in the zowe-explorer package)
- src/IZoweTreeNode.ts (Declarations only. The below functions are specific to IZoweUssTreeNode only):
  - `refreshUSS?()`: Refreshes the passed node with current mainframe data. (Function definition is in ZoweUSSNode.ts.)
  - `refreshAndReopen?(hasClosedInstance?: boolean)`: Refreshes node and reopens it. (Function definition is in ZoweUSSNode.ts)

*In the `zowe-explorer` package*
- src/abstract/ZoweTreeProvider:
  - `refreshElement(element: IZoweDatasetTreeNode)`: Called whenever the tree (tree element?) needs to be refreshed, and fires the data change event
    - Marks element as dirty, then calls `mOnDidChangeTreeData` on the element in the tree provider.
  - `refresh()`: Called whenever the tree needs to be refreshed, and fires the data change event
    - Calls `mOnDidChangeTreeData` on the tree provider.
- src/dataset/actions:
  - `refreshAll(datasetProvider: IZoweTree<IZoweDatasetTreeNode>)`: Refreshes treeview
  - `refreshPS(node: IZoweDatasetTreeNode)`: Refreshes the passed node with current mainframe data, where "node" represents the data set.
- src/uss/actions:
  - `refreshAllUSS(ussFileProvider: IZoweTree<IZoweUSSTreeNode>)`: Refreshes treeview
  - `refreshUSSInTree(node: IZoweUSSTreeNode, ussFileProvider: IZoweTree<IZoweUSSTreeNode>)`
    - Seems to just call `refreshElement` on the node in the tree.
- src/uss/ZoweUssNode:
  - `refreshUSS()`: Refreshes the passed node with current mainframe data 
  - `refreshAndReopen(hasClosedInstance = false)`: Refreshes node and reopens it
- src/job/actions:
  - `refreshAllJobs(jobsProvider: IZoweTree<IZoweJobTreeNode>)`: Refresh all jobs in the job tree.
  - `refreshJobsServer(node: IZoweJobTreeNode, jobsProvider: IZoweTree<IZoweJobTreeNode>)`: Refresh a node in the job tree
- src/shared/utils.ts:
  - `refreshTree(sessNode: IZoweTreeNode)`:  Refresh Profile and Session
  - `labelRefresh(node: vscode.TreeItem)`: Not actually a tree refresh, but just a silent label rename to force a node to repaint.
- src/utils/ProfileUtils.ts:
  - `refreshTree(sessNode: IZoweTreeNode)`:  Refresh Profile and Session

**Outside-in view/use case scenarios**
(See [comment](https://github.com/zowe/vscode-extension-for-zowe/issues/1048#issuecomment-717345935) below.)

**Areas of potential improvement**
- Name refresh functions more descriptively to better differentiate them and what they do.
- Consider breaking the refresh in Profiles.ts down into smaller functions.
```[tasklist]
### Tasks
- [ ] #1079
```

**Comment by lauren-li** [comment]
Outside-in view/use case scenarios:
TBA

Inconsistencies in the refresh UX:
TBA

**Comment by crawr** [comment]
Thanks for your hard work on putting this together, @lauren-li ! 

The only thing I could add under USS tree is the Toggle Binary/Text command. Currently, when I select this option, all the expanded folders are also refreshed. Ideally, only the parent node of the file is refreshed.

**Comment by jellypuno** [comment]
> src/Profiles.ts:
> refresh():
> Gets base profiles
> Gets extender profiles
> Get an array of all profiles (Profiles.allProfiles)
> Get an array of all profile types (Profiles.allTypes)
> Remove all profiles from profilesForValidation array (profiles.profilesForValidation)

Additional to this, call getCombinedProfiles because once it is refreshed the allProfiles array doesn't contain the combined profiles.

**Comment by lauren-li** [comment]
Potential issue (currently investigating):
Refresh button does not seem to be reloading extenders' profiles anymore.

**Comment by lauren-li** [comment]
Thanks everyone for your input on this so far!

I've updated the issue description with changes that were made to the monorepo, and updated the outside-in use cases with @craw's comment.

@jellypuno I'm a little confused about `getCombinedProfiles`.  Are you saying it is currently called as part of the `refresh` function in `src/Profiles.ts` (or apparently `src/ProfilesCache.ts` now)? Or are you saying we should add it in there? I looked in `master` branch, but only see it being called in each tree's `addSingleSession` function. I do not see it in either of the `refreshTree` functions, either.
- Regarding each tree's `refreshAll` function, the API seems to already have a `refresh` function that refreshes a tree, and it appears to be defined in `zowe-explorer/src/abstract/ZoweTreeProvider`. It seems a bit more general than the `refreshAll` functions, though. I think the answer to your question may depend on whether we want to merge the functionality of these two implementations of tree refresh functions.

**Comment by lauren-li** [comment]
In `refreshTree` of `packages/zowe-explorer/src/shared/utils`, the following line appears to always evaluate to `True`, even if no changes were made to the profile (tested with z/OSMF profiles):
`if (sessNode.getSession().ISession !== SessionProfile)`

It appears that the two sides of the equation return different objects. This means that this function is always going to update Zowe Explorer's profile from its yaml file, even if nothing has been changed. It is not necessarily harmful during the refresh, but it is just an extra check and extra step.
- `sessNode.getSession().ISession` returned an object containing values for the following keys:
  1. base64EncodedAuth
  1. basePath
  1. hostname
  1. password
  1. port
  1. protocol
  1. rejectUnauthorized
  1. secureProtocol
  1. strictSSL
  1. type
  1. user
- `SessionProfile` returned an object containing values for the following keys:
  1. basePath
  1. encoding
  1. host
  1. password
  1. port
  1. rejectUnauthorized
  1. responseTimeout
  1. user

**Comment by lauren-li** [comment]
@zdmullen I've created a low-hanging fruit graph to map out the value/effort for the issues we currently have listed as related to refresh:

<img width="565" alt="Screen Shot 2020-12-03 at 10 14 46 AM" src="https://user-images.githubusercontent.com/45975633/101048321-85993c00-3550-11eb-8a31-d48128222095.png">

As for the issues that did not make it into the graph, I have categorized them as follows:
- Validating/Done:
  - #1078 Tree Refresh button does not pick up extenders' profile updates

- Possibly related to refresh:
  - #471 Refresh of DS is taking long time (This may be related to the way we pull things from mainframe, or it may be related to calls we make within the refresh function.)

- Not related to VS Code UI refresh (i.e. not planned to be addressed as part of the Refresh Refactor):
  - #755 eTag error encountered when saving file in root of USS tree
  - #988 Enable update of Job Logs (This is more related to pulling from mainframe)
  - #832 Refresh DS members without having to individually select them (This is more related to pulling from mainframe)
  - #1033 Clear all settings and default profile in meta yaml to null if profiles are manually deleted (This should be fixed in the code to add session/add single session.)

**Comment by lauren-li** [comment]
Suggestions/considerations for refresh functions:
- `refreshAll`/`refreshAllUSS`/`refreshAllJobs` in `actions.ts` file (datasets, uss, and jobs): Perhaps take this function and put it in a shared file (maybe `src/shared/utils.ts`?), as the code appears to be identical between all 3 trees.
    - There are also two `refreshAll` functions defined: One in `dataset/actions.ts`, and one in `dsNodeActions.ts`. Perhaps one of those can be removed.
    - This function skips refreshing favorites (if (contextually.isSessionNotFav(sessNode))) – should we take this snippet out so `refreshAll` refreshes favorites, as well?

- `refreshUSSInTree`: Could we refactor this out, and just use `ussFileProvider.refreshElement(node)` directly?

- `refreshJobsServer`: Is this being used anywhere? Can we delete this function?

- `refreshPS` and `refreshUSS`: Consider renaming these, as they do not involve UI refresh. (However, they are “refresh” in the sense of “refreshing a file/data set with the latest content from the mainframe”.)

- `refreshTree`:
    - There is a `refreshTree` defined in `src/utils/ProfileUtils.ts`, and one defined in `src/shared/utils.ts`. Is there a difference in purpose between these two functions? The one in `ProfileUtils` looks kind of the same as the one in shared/utils, except not updated for base profiles. It is just used in getDatasets, getJobs, getChildren (USS).
    - (The `refreshTree` in shared/utils is just used by the `refreshAll-` functions.)
    - This function does not do anything directly related to refresh. Perhaps we could rename it to, `getUpdatedProfiles`). (Actually, I think `refreshTree` is a better function name for what the `refreshAll` functions currently do…)

**Comment by lauren-li** [comment]
I am creating tables to categorize user actions into different types of refresh.

- Refresh level:

  - View: Refresh the entire view, i.e. Data Sets (MVS), USS, or Jobs
  - Node: This is any node inside a view, whether it is a session node, parent node, file/folder, etc.

- Info flow: In which direction is information being sent?

  - Client>Host: Client telling mainframe the "truth"
  - Host>Client: Mainframe telling client the "truth"

- Automatic/Manual: Automatic versus manual refresh

- Notes: Additional notes

## Non-profile methods

| Method/Command          | Refresh level | Info flow   | Automatic/Manual | Notes                               |
| ----------------------- | ------------- | ----------- | ---------------- | ----------------------------------- |
| Create (MVS, USS, Jobs) | Node          | Client>Host | Automatic        |                                     |
| Rename (MVS, USS)       | Node          | Client>Host | Automatic        | Renaming folder changes child paths |
| Delete (MVS, USS, Jobs) | Node          | Client>Host | Automatic        |                                     |

## Profile methods

| Method/Command  | Refresh level | Info flow   | Automatic/Manual | Notes |
| --------------- | ------------- | ----------- | ---------------- | ----- |
| Create (via ZE) | View          | Client>Host | Automatic        |       |

**Comment by JillieBeanSim** [comment]
Working on a fork for the refresh refactoring https://github.com/JillieBeanSim/vscode-extension-for-zowe/tree/refresh-refactoring

So far 
- `refreshAll`/`refreshAllUSS`/`refreshAllJobs` in actions.ts file (datasets, uss, and jobs) have been removed and all calls are using refreshAll() in the new /shared/refresh.ts file.
- `dsNodeActions.ts` has been removed since all it had was another refreshAll() method
