### ISSUE TITLE
When using Toggle Binary/Text command, only refresh parent node.

### ISSUE THREAD

**Issue by lauren-li** [zowe/zowe-explorer-vscode#1079]
**Describe the bug**
Currently, when the user selects the Toggle Binary/Text option for a USS file, all the expanded folders are also refreshed. Ideally, only the parent node of the file is refreshed.

**To Reproduce**

1. Right click on a USS file, and select "Toggle Binary" or "Toggle Text".
2. See (via VS Code information messages), that refreshes are occurring for all expanded folders.

**Expected behavior**

Only the parent node of the file that was toggled is refreshed.

**Desktop (please complete the following information):**

- OS: Issue occurs on Windows and Mac
- Zowe Explorer Version: 1.10.1
- (Optional) Zowe CLI Version: 6.22.0
- (Optional) Are you using Secure Credential Store? Issue occurs with and without SCS.

**Comment by JillieBeanSim** [comment]
toggle binary has been replaced by another method of handling code pages
