### ISSUE TITLE
Filtered data sets can't be added to favorites

### ISSUE THREAD

**Issue by katelynienaber** [zowe/zowe-explorer-vscode#1164]
**Is your feature request related to a problem? Please describe.**

If a member filter is present on a data set, and I add the data set to favorites, it has the wrong icon in favorites (member filter icon) and the favorite disappears after refreshing the workspace. This is why we have removed the favorites button from filtered nodes for now.

**Describe the solution you'd like**

I should be able to favorite a data set with the member filter on it, or one of its members.

**Comment by JillieBeanSim** [comment]
related issue https://github.com/zowe/vscode-extension-for-zowe/issues/1362

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.

**Comment by adam-wolfe** [comment]
We should revisit this. Users are able to favorite a filter with wildcards in the data set name, however they cannot save a favorite where there are wildcards in the member name. 
![save-member-filter](https://github.com/zowe/zowe-explorer-vscode/assets/122040687/56028d88-370e-406a-9860-cc4b9231eb7a)
