### ISSUE TITLE
Rename the repository to `zowe-explorer`

### ISSUE THREAD

**Issue by VitGottwald** [zowe/zowe-explorer-vscode#1237]
The fact that our repository is called `vscode-extension-for-zowe` on github, but ZOWE Explorer elsewhere (marketplace, ZOWE docs) is somewhat confusing.

Could we consider renaming this repository to `zowe/zowe-explorer`?
```[tasklist]
### Update references to old repo name
- [x] zowe/zowe-explorer-vscode
- [x] zowe/zowe-cli-install-packaging
- [x] zowe/zowe-cli-standalone-package
- [x] zowe/zowe-dependency-scan-pipeline
- [x] zowe/docs-site
- [x] zowe/zowe.github.io
```

**Comment by t1m0thyj** [comment]
I support the idea of renaming the repository 🙂 When I want to access the ZE GitHub repo, I often type "zowe explorer" in my address bar expecting the URL to appear from my browsing history, but it doesn't because ZE isn't the repo name.

**Comment by crawr** [comment]
Hi All, 

As per our last discussion, it is our squad's decision if we want to go ahead and change our repository name. The suggested new name would be `zowe-explorer-vscode`.  We would like to call for a vote if we want to proceed with this change.

Before voting, here is a reminder of some of the implications brought up during the discussion:
1. Documentation changes. There would be a huge amount of change in docs including zowe doc-site, zowe website, readMe files from existing extensions, blogs and other articles. GitHub might have mitigation for this in the form of link redirects for a short amount of time.
2. We need to inform other squads and stakeholders about this change.
3. Does the unique identifier also need to be changed in the future? 

Please vote using the reactions below:
❤️ -> I agree with the change of repository name to `zowe-explorer-vscode`
😕 -> I have more questions, comments, concerns 
👀 -> No change

**Comment by jellypuno** [comment]
Just a note so we wont forget, this change in repo name will be implemented on ZE V2

**Comment by IgorCATech** [comment]
I think we should be more mindful of these potential changes. Can I ask everyone to answer the following questions before making any decisions:
- What value do we get from this rename?
- Who amongst our customers had/has concerns about the current name? 
- What's going to happen to SEO? Currently, if one Googles "zowe explorer repository", the first link s(he) gets is exactly the link to our repo. See https://prnt.sc/10ud474 that illustrates the point.
- Are we cognizant of all our users who have saved the existing link to the repo? Can we provide a redirect link?
- What are the repercussions for marketing/education/other departments?

Here's the list of products/teams, that I can come up with off the top of my head, that will be affected:

1. Brightside docs
2. Code4z
3. Zowe Docs/Zowe website
4. Marketplace ReadMe
5. Some blogs where the links to the Marketplace ReadMe was used
6. Presentations/Demos/Videos (?) Maybe these are not so important
7. Stakeholders that are part of the abovementioned products.

It's probably not a complete list.

**Comment by phaumer** [comment]
I would like to vote for the original name proposal `zowe/zowe-explorer`. As we are the Zowe Explorer squad we should be able to claim that name. Plus, there are packages in the API that are meant to be independent of VS Code and can be reused in other scenarios such as CLI plugins. Plus, if we would support other IDEs in the future we would want to do this in the same repo reusing common code as much as possible, which was one of the reasons we switched to a monorepo. Also, we already do run in other environments such as Theia, Che, VSCodium.

**Comment by VitGottwald** [comment]
> What's going to happen to SEO? Currently, if one Googles "zowe explorer repository", the first link s(he) gets is exactly the link to our repo. See https://prnt.sc/10ud474 that illustrates the point.

Actually this is part of the problem. People do not type the extra word `repository` when searching. When we enter `zowe explorer` to google the link to the repo is the last one on the first page. On the other hand when we type in `zowe cli` the github repo is the first link that google returns.

So if we renamed the repo to `zowe-explorer` I believe the SEO will clearly improve. If we rename to zowe-explorer-vscode, I would still expect it will get better, but I am not sure.

**Comment by VitGottwald** [comment]
> Can we provide a redirect link?

Github redirects to the new name automatically. Searching around, it looks like the redirect will be in place, until a new repository is created with the original name. https://github.community/t/how-long-does-github-forward-renamed-moved-repos/582

**Comment by VitGottwald** [comment]
> What value do we get from this rename?

Making the repository easier to find when people search for `zowe explorer`.

**Comment by jellypuno** [comment]
More info about renaming a repository: https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by MarkAckert** [comment]
None that haven't been brought up earlier in thread - namely external references made by third parties. I don't have anything new to add to the discussion, so if the squad believes those concerns are in hand then I'm OK with the rename to `zowe-explorer-vscode`.

One request I have as part of this issue is to please include an update to the [tracking manifest.json](https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/manifest.json.template). Thanks

**Comment by t1m0thyj** [comment]
The repo has been renamed to `zowe-explorer-vscode`. Tasks that remain:

* [ ] Update references to the old repo name in our own repo ([search results](https://github.com/search?q=org%3Azowe+vscode-extension-for-zowe+repo%3Azowe%2Fzowe-explorer-vscode&type=code))
* [ ] Update references to the old repo name across other Zowe repos: 
  * [ ] [zowe-cli-install-packaging](https://github.com/search?q=org%3Azowe+vscode-extension-for-zowe+repo%3Azowe%2Fzowe-install-packaging&type=code)
  * [ ] [zowe-cli-standalone-package](https://github.com/search?q=org%3Azowe+vscode-extension-for-zowe+repo%3Azowe%2Fzowe-cli-standalone-package&type=code)
  * [ ] [zowe-dependency-scan-pipeline](https://github.com/search?q=org%3Azowe+vscode-extension-for-zowe+repo%3Azowe%2Fzowe-dependency-scan-pipeline&type=code)
  * [ ] [zowe.github.io](https://github.com/search?q=org%3Azowe+vscode-extension-for-zowe+repo%3Azowe%2Fzowe.github.io&type=code)
  * [ ] [docs-site](https://github.com/search?q=org%3Azowe+vscode-extension-for-zowe+repo%3Azowe%2Fdocs-site&type=code)
* [ ] Rename OMP Slack channel from #zowe-explorer-vsce to #zowe-explorer-vscode
