### ISSUE TITLE
JOBS - Enhance management / new Zowe Explorer Extension for JOBS

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-explorer-vscode#1597]
**Describe the solution you'd like**

The management of JOBS in Zowe Explorer is very limited and only displays a list of jobs retrieved from the remote z/OS system.

In real use, especially for a developer, the following features should be available:

- distinguish the different JES QUEUEs

A job can be in 3 states, ie appear in one of the 3 JES QUEUEs: the input QUEUE, the job is not started, the active QUEUE, the job is being executed, the output QUEUE, the job is finished.

- sort jobs

The list of jobs can be long and each user can have their preferences for finding / administering their jobs.
Some prefer to sort their jobs on the jobname, others on the jobid, others on the submission time (read time), others on the start time, others on the return code, and each JES QUEUE can be sorted on different criterias.
Job sorting must be local to Zowe Explorer and must not require a new job retrieval from the remote z/OS server.

- local filtering

Zowe Explorer allows you to filter / select jobs when retrieving from the remote z/OS server.
For job administration needs, it could be interesting to add a local filtering at the display level in Zowe Explorer.
For example, filtering jobs that have a return code greater than or equal to 8.

- tabular display

Zowe Explore uses a hierarchical display of jobs retrieved from the remote z/OS server.
This is not the usual way of working on jobs for z/OS users because whatever software is usually used (IBM SDSF, CA SYSVIEW ...), the jobs are presented in tabular form.
Zowe Explorer should also offer a tabular display of jobs, with the possibility of sorting, filtering, selecting the columns of the properties to display, and triggering actions on the jobs: purge, release, cancel ...

**Describe alternatives you've considered**

Develop an extension, **Zowe Explorer Extension for JOBS**, perhaps using the Zowe Explorer Extensibility API, to reproduce in VS Code, with limited functionnalities to Zowe CLI jobs capacities, the operation of software such as IBM SDSF or CA SYSVIEW, like Zowe Explorer Extension for FTP or Zowe Explorer for IBM CICS.

Such an extension should also allow access to the MVS log.

```[tasklist]
### Tasks
- [ ] #1685 
- [ ] #1951
- [ ] #2061
- [ ] #2255
- [ ] #2256 
- [ ] #2257 
- [ ] #2308
```

**Comment by zFernand0** [comment]
Hey Denis,
 Thanks for linking each individual issue by leaving a comment on them 😋 
 Truly appreciated! 🙏🏽 
 
 For those interested in seeing these issues in a more Kanban format...
 - Feel free to go to our [ZenHub page](https://app.zenhub.com/workspaces/explorer-squad-workspace-6017d05aab554d0010a83a57/issues/gh/zowe/vscode-extension-for-zowe/1597) OR
 - You can install the [ZenHub extension for your browser](https://www.zenhub.com/extension), and you should be able to see a view like the following:
     ![image](https://user-images.githubusercontent.com/37381190/236851284-b4aaed82-9d76-432c-a2cc-961d74354d44.png)

**Comment by JillieBeanSim** [comment]
closing as all tasks are complete 🎉
