### ISSUE TITLE
Integration tests unable to read property 'restore' of undefined

### ISSUE THREAD

**Issue by lauren-li** [zowe/zowe-explorer-vscode#1621]
**Describe the bug**

I am often unable to completely run Zowe Explorer's integration tests due to an issue with an `after each` hook. Occasionally (maybe 20-30% of the time), I can get past the MVS tests, but usually they fail with the following message in the Debug Console:

<img width="566" alt="Screen Shot 2021-12-22 at 9 22 21 AM" src="https://user-images.githubusercontent.com/45975633/147108175-6bb877e7-6ec9-4eeb-b911-41ca5bb95f74.png">

According to this error message, the issue appears to be coming from line 102 of `packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts`, where `sandbox` is undefined when the test reaches it:

<img width="598" alt="Screen Shot 2021-12-21 at 12 38 57 PM" src="https://user-images.githubusercontent.com/45975633/147108957-513922b7-577d-4d67-a561-6cdb984a62c1.png">

**To Reproduce**

1. Perform all setup steps needed to run integration tests as specified in Zowe Explorer's [developer docs](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Developer.md#run-system-tests), plus have a valid TSO profile in `packages/zowe-explorer/resources/testProfileData.ts`
2. [Run the integration tests](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Developer.md#executing-from-vsc)
3. The integration tests stop without completing with the following error in the Debug Console:
     ```
     1) "after each" hook for "should submit a command":
         TypeError: Cannot read property 'restore' of undefined
     ```

**Expected behavior**

The integration tests can run completely.

**Desktop (please complete the following information):**

- OS: MacOS and Windows
- Zowe Explorer Version: 1.21.0 (but I have had this issue in previous versions, too)
- (Optional) Are you using Secure Credential Store? No, not when running integration tests.

**Additional context**

Thanks, @jellypuno for helping me test and debug this on Windows!

**Comment by traeok** [comment]
Closed as not planned - we now use a new set of integration tests w/ WebDriver
