### ISSUE TITLE
Copy data set name to clipboard

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-explorer-vscode#1634]
**Describe the solution you'd like**

I would like to copy the data set name that I see in the DATA SETS view into the clipboard.

I can copy the path to a file in the standard Visual Studio Explorer and I would like to copy the data set name, member name, or dataset.name(member) to clipboard. I will then paste it elsewhere a document or command line (with Zowe CLI command).

**Describe alternatives you've considered**

I can copy the longer path when I right-click the opened tab with a member from the dataset:

```
/Users/hello12/.vscode/extensions/zowe.vscode-extension-for-zowe-1.21.0/resources/temp/_D_/ab12/MFAAS.SDKRES.MFSI.CAI.SAMPJCL(AREADME)
```

Or I can get JSON when I use "Copy Member" on a member:

```json
{"profileName":"ab12","dataSetName":"MFAAS.SDKRES.MFSI.CAI.SAMPJCL","memberName":"AREADME"}
```

That means that I need to paste the longer text somewhere else and take the part that I need. I would rather get just the plain DSN or member name so I can simply paste it.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.

**Comment by adam-wolfe** [comment]
This functionality was added in Zowe Explorer V3.0.
