### ISSUE TITLE
characters transformed in the result of JOBS

### ISSUE THREAD

**Issue by ROBIN-Olivier** [zowe/zowe-explorer-vscode#1941]
In the JOBS SYSOUT, accented characters like "é" or "è" are replaced by "{" or "}".
Yet these characters are displayed fine in a file opened in VSCODE
How to apply code page 1147 to the SYSOUT of JOBS?

1. write a program that displays é, è, à
2. write a jcl that executes program
3. open the runtime log in VSCODE
-->

**Expected behavior**

our code page 1147 should not apply here.

**Screenshots**

result with TSO : Début ...
![caractères bien affichés dans sysout TSO](https://user-images.githubusercontent.com/103997342/191572594-2978d856-5db7-4cb4-ab71-42f45e5b2132.png)

result with VSCODE : D{but ...
![caractères mal affichés dans sysout VSCODE](https://user-images.githubusercontent.com/103997342/191572623-0a589a3e-35a4-4f4b-86e5-77e76135e3a2.png)

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: v2.3.0

**Comment by ROBIN-Olivier** [comment]
Hi,
It's zosmf

Olivier ROBIN
Centre de Compétences Modernisation des SI et Mia-Software
[26A14E96]
11 rue Nina Simone
BP 70908
44009 Nantes Cedex 1
Mobile: +33 (0)6 26 36 36 37
***@***.******@***.***> - www.soprasteria.fr
Suivez-nous sur : LinkedIn<https://www.linkedin.com/company/soprasteria>  |  Twitter<https://twitter.com/SopraSteria_fr>  |  Facebook<https://www.facebook.com/soprasteria>

Le contenu de cet e-mail est susceptible d'être confidentiel, soumis au secret professionnel ou protégé par la loi. L'utilisation, la copie et la divulgation non autorisées d'une partie ou de l'intégralité de ce message sont susceptibles d'être illicites. Si vous avez reçu ce message par erreur, supprimez-le après avoir averti l'expéditeur. Les pièces jointes au présent e-mail ont fait l'objet d'un contrôle antivirus. Néanmoins, Sopra Steria Group et ses filiales déclinent toute responsabilité concernant les dommages causés par d'éventuels virus, ainsi que pour tout retard, erreur, altération ou modification affectant la remise ou le contenu du présent email ou de ses pièces jointes.
Pensez à l'environnement avant d'imprimer.

Si vous recevez ce message pendant vos temps non travaillés, il ne requiert ni prise de connaissance, ni réponse immédiate de votre part.



C2 - Usage restreint
De : Billie Simmons ***@***.***>
Envoyé : jeudi 22 septembre 2022 16:46
À : zowe/vscode-extension-for-zowe ***@***.***>
Cc : ROBIN Olivier ***@***.***>; Mention ***@***.***>
Objet : Re: [zowe/vscode-extension-for-zowe] characters transformed in the result of JOBS (Issue #1941)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Hey @ROBIN-Olivier<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FROBIN-Olivier&data=05%7C01%7Colivier.robin2%40soprasteria.com%7C831517431a4a42e3047f08da9ca922ba%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C637994547489834080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QVlZgTxwvXOckHPuhqNJqSWkLAZxd2nsIpPh93UgXEc%3D&reserved=0>, what profile type are you using to connect to the host?

-

**Comment by traeok** [comment]
This issue also applies for submitting jobs - this should probably be addressed at the same time as spool encoding for a complete experience

**Comment by t1m0thyj** [comment]
The "Open with Encoding" feature for spool files has been implemented and will be released in 3.1.0
