### ISSUE TITLE
V1-LTS Technical Currency

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#1949]
Update dependencies for our V1 LTS version
https://github.com/zowe/vscode-extension-for-zowe/security/dependabot

**Comment by zFernand0** [comment]
I'm afraid that the only things that dependabot reports are on the default (`main`) branch.
After reviewing the `v1-lts` branch, we don't have any production vulnerabilities reported by yarn or npm
These are the recommendations:
- Update `jest@27.x`
- Update `geckodriver@>=3.0.2`
- Update `eslint@^6.8.0`

**Comment by zFernand0** [comment]
Moving this to a v1.22.3 milestone in case we want to update these dependencies and maybe port back the following PR:
- #2017

**Comment by JillieBeanSim** [comment]
@zFernand0 can this be closed with v1 going out of support Sept 2024? I think we can address vulnerabilities as they come until eos.
FYI @adam-wolfe

**Comment by zFernand0** [comment]
YEah, I think this can be closed. We have a PR updating some dependencies for V1, so maybe we close this a part of that release PR: 
- #2815
