### ISSUE TITLE
[V1] Update workflows to work with node16 and node18

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2003]
This may require some fixes to our tests :yum:

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/pull/1996#discussion_r1016789693_

**Comment by zFernand0** [comment]
Moving to v1.22.3 in case we identify issues with newer versions of node.
If no end-user problems are identified by then, we can continue building v1 with `node12` until GitHub removes it from their labeled versions of node 😋

**Comment by JillieBeanSim** [comment]
matrix updated for 14, 16, & 18
https://github.com/zowe/zowe-explorer-vscode/blob/v1-lts/.github/workflows/zowe-explorer-ci.yml
