### ISSUE TITLE
Support for Drag-Drop within VSCode

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2046]
**Is your feature request related to a problem? Please describe.**

Seeing how easily the Intelij Zowe Explorer plugin is able to download and upload files by dragging them around, should we support such functionality on the VSCode Zowe Explorer extension

**Describe the solution you'd like**

This GIF should help: 😋 
![zowe-explorer-drag-and-drop](https://user-images.githubusercontent.com/37381190/207681354-65439c55-bc31-40b2-9f22-f105ca37a76d.gif)

**Describe alternatives you've considered**

The workaround is to do regular download and upload operations 😅 

**Additional context**

Inspired by today's Zowe Q4 Webinar.

**Comment by JillieBeanSim** [comment]
@traeok should this item be added to the tree provider PR as it brings in the capability?

**Comment by traeok** [comment]
> @traeok should this item be added to the tree provider PR as it brings in the capability?

Yes - thanks for spotting this! Added 👍

**Comment by traeok** [comment]
Closed as the infrastructure was implemented for Zowe trees in #2777
