### ISSUE TITLE
`Actual command not found` error when double-clicking USS file

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2124]
**Describe the bug**

When double-clicking on a USS file in a directory, VScode now prints an error that the command for `zowe.uss.ZoweUSSNode.open` was not found - it looks like there is an issue with a number being appended to the end of the command, therefore breaking the command name that is going to be executed.

**To Reproduce**

1. Search for folder in USS panel
2. Open folder
3. Double-click on a file in said folder
4. Notice error that appears

**Expected behavior**

The node should open a text document after the double-click event occurs.

**Screenshots**

![image](https://user-images.githubusercontent.com/86500639/218188748-0d94f1b7-78cd-4281-aad2-a9058352656d.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.6.0

**Comment by traeok** [comment]
This issue appears to have been caused by VS Code v1.75:

https://github.com/microsoft/vscode/issues/173233

We will monitor this issue and update with more info.

**Comment by phaumer** [comment]
@traeok I can see it every time when I double click a PDS member node on a Windows VM as well.

**Comment by traeok** [comment]
> @traeok I can see it every time when I double click a PDS member node on a Windows VM as well.
> 
> 
> 
> Does the change for v3 actually mean that we can use double-click to keep the editor tab open? Because of muscle memory I do double-click by default now.

Hi @phaumer, with v3 all double-click actions work as intended and no error messages will appear. You'll be able to leverage VSCode's default behavior of double-clicking on a resource in the tree to keep it open in the editor. Single click will open in preview mode as usual.

**Comment by traeok** [comment]
Closing as not planned for v2 as this is due to how VS Code processes command execution. This is resolved in v3.
