### ISSUE TITLE
LSP didClose event not created on close of dataset member

### ISSUE THREAD

**Issue by ishche** [zowe/zowe-explorer-vscode#2154]
**Describe the bug**

LSP didClose event not created on close of dataset member. It prevents language support for source code in dataset members.

**To Reproduce**

1. Install COBOL LS extension
2. Open a dataset with a COBOL program, and enable COBOL language for the file if it's not triggered automatically.
3. Make an error in the program
4. Close the member
5. Observe the error in the problems view.

**Expected behavior**

No errors should stay in the problem's view.

**Additional context**

COBOL LS removes errors on didClose event. According to logs, there was no didClose event fired on the close of the editor with a member.

**Comment by VitGottwald** [comment]
I just tested this and in my case the errors actually disappeared, but with a delay of about 5 seconds.

**Comment by ishche** [comment]
> I just tested this and in my case the errors actually disappeared, but with a delay of about 5 seconds.

Well, for me (on mac and windows) it's never... or more than 5 minutes.

**Comment by zimlu02** [comment]
Any progress on this one, please?

**Comment by zFernand0** [comment]
In case it helps, we have considered that this issue could be resolved at the same time we implement an FS Provider
More detaiils:
- #2207

**Comment by VitGottwald** [comment]
It appears that https://github.com/zowe/zowe-explorer-vscode/pull/2777 fixes this issue.
