### ISSUE TITLE
`Pull from Mainframe` is adding extra characters to each record/line

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2169]
When I right click on the member name and click "Pull from mainframe" it adds 1 space in front of each line of the JCL. So I delete that line, save the member and try to re-run the job and it still gives me this same error. I am not sure what is causing this reformat to happen, but it basically makes the option to use zowe through vs code unusable...

_Originally posted by @LukeG-96 in https://github.com/zowe/vscode-extension-for-zowe/issues/1116#issuecomment-1453877960_

**Comment by zFernand0** [comment]
Personally, I thought this could be related to a race condition in how we save and upload contents to the mainframe
- Details: https://github.com/zowe/vscode-extension-for-zowe/pull/2164

---

From _`@LukeG-96`_:

I get the "Data Set Uploaded successfully" message but when I follow the steps you suggested it still puts one space in front of every line and adds a new line at the bottom...

Below is what is looks like after I make my changes and save the member:
![image](https://user-images.githubusercontent.com/126080946/222794372-76ea0718-9f6a-4088-b596-2c923f1756bb.png)

Here is what it looks like after I issue a **Pull from mainframe**
![image](https://user-images.githubusercontent.com/126080946/222794469-4cc8cebd-e7db-461b-ac97-005f10023680.png)

**Comment by zFernand0** [comment]
Hey  @LukeG-96 ,
Could you share the attributes of the dataset?
I tried a few things and I still cannot reproduce the `Pull from mainframe` adding an extra space.

List of things I tried:
- Data-loss issue in previous versions of Zowe Explorer (v2.6.2 and earlier)
  - With this mechanism I was able to reproduce the fact that my "edits" (i.e. removing all spaces at the front of each line) were not successfully uploaded, even though VSCode said otherwise. 
  - Because of this, I was getting the spaces back after every `Pull from Mainframe`
  - Note: this was resolved in 2.7.0 (and I couldn't reproduce it the same way)
- CR/LF differences
  - I tried uploading content with different line-endings and `pull from mainframe` would just convert the line endings automatically (depending on the OS - Windows: CRLF | *nix - LF)
  - Result: no spaces being added to each line
- Record datasets
  - I tried downloading and uploading datasets and the only way to get it to fail was uploading a record-type dataset in binary format (to a PDS with variable record format)
  - This failure was expected since the first couple of bytes basically describe the the record length and it is not valid JCL
  ![image](https://user-images.githubusercontent.com/37381190/227247307-4136f479-dbf2-400f-a77b-ae9d1db2117b.png)
- Encoding differences
  - Results: Similar to the CR/LF, no spaces being added to each line
  - In this case, z/OS takes care of the conversion and the data/JCL should be fine as long as we don't change to a codepage that is fundamentally different.

**Comment by FALLAI-Denis** [comment]
Hi,

Similarly, pulling a file or a member from the mainframe adds a blank line to the end of the downloaded file, i.e. adds a newline after the last line which creates a blank line.

**Comment by zFernand0** [comment]
> Similarly, pulling a file or a member from the mainframe adds a blank line to the end of the downloaded file, i.e. adds a newline after the last line which creates a blank line.

Hey @JillieBeanSim, should we create an issue for this particular behavior?

**Comment by JillieBeanSim** [comment]
@zFernand0 I would assume it would be handled along with this issue since newline = newline char at end of line
