### ISSUE TITLE
Support multiple v1 profiles with same name and different types

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2197]
Since v2 profiles always have unique names, we have some logic in ZE that assumes profile names are unique and searches for profiles by name to match a session node to a profile.

When using v1 profiles, it is possible to have a "zosmf" and "zftp" profile both with the same name "lpar1". This could cause a few issues:
* In the [`errorHandling`](https://github.com/zowe/vscode-extension-for-zowe/blob/6fa16aad1897aa1fa339cc16fe10662991b724ec/packages/zowe-explorer/src/utils/ProfilesUtils.ts#L37) method, we use a session label to match a profile. When handling an error for the "zftp" profile, we may incorrectly match the "zosmf" profile instead since it has the same name.
* If a data set with the same name is opened in both the "zosmf" and the "zftp" session, the temp paths where the file is cached on disk may conflict since they would both be `_D_/lpar1/<dsname>`.

Tagging this as low priority since it only affects v1 profiles which are soon to be deprecated, and if multiple v1 profiles have the same name they likely point to the same LPAR and share the same credentials and filesystem. If this issue is encountered, a workaround would be to rename one of the profiles so that the names are different.

**Comment by JillieBeanSim** [comment]
@t1m0thyj is this something we still plan to do with v1 going out of support in Sep 2024?
FYI @adam-wolfe 
If not we can close as won't do.

**Comment by t1m0thyj** [comment]
Probably not, closing 🙂
