### ISSUE TITLE
Use `vscode.FileSystemProvider` for content downloaded from mainframe

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2207]
Replace our usage of a temp download folder on disk with an in-memory file system provider. I think there are a lot of benefits that would result from this switch, but it is a significant change to ZE architecture so I suggest we start with a spike story to investigate/research it first and share results with the team before undertaking it.

**Benefits**
* Could hook into save event for better error handling/dirty detection
* Could use `vscode.open` for automatic double-click detection in trees
* More TBD

**Resources**
* https://code.visualstudio.com/api/extension-guides/virtual-documents
* https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample
* https://github.com/liximomo/vscode-remote-fs/blob/master/src/core/RemoteFileSystemProvider.ts

**Comment by t1m0thyj** [comment]
Spike for 23PI2 to investigate pros and cons of adopting the FIleSystemProvider API and document expected breaking changes.

**Comment by VitGottwald** [comment]
An interesting aspect - from the extenders point of view - would be the ability to request dataset content or list of PDS members by reading ZOWE Explorer provided file system URL rather than having to issue download requests. Similarly for jobs and uss files.

**Comment by t1m0thyj** [comment]
Proposed URI scheme to access resources through a FileSystemProvider:
`zowe://<treeId>/<profileName>/<resourcePath>?<options>`

* `<treeId>` is an ID associated with a tree provider that provides the resource ("ds", "uss", "jobs", "cics")
* `<profileName>` is the name of a profile to be used to access the resource (e.g., "lpar1.zosmf", "lpar1.zftp")
* `<resourcePath>` is a path to uniquely identify the resource (data set, USS file, job spool file, etc)
  * For "ds", it would be a data set (and member) name (e.g., `IBMUSER.PS`, `IBMUSER.PDS(MEMBER)`)
  * For "uss", it would be a USS path (e.g., `/u/ibmuser/test.txt`)
  * For "jobs", it could be similar to the name we currently use: `<jobname>.<jobid>.<ddname>`
* `<options>` allows request parameters to be passed (e.g., `binary=true`)

Advantages:
* No local filesystem required since we don't have to store files on disk in a temp folder anymore
* Breadcrumb at top of editor is a convenient alternative to trees for navigating mainframe resources
* Resource can be opened in ZE by issuing a CLI command - for example to open a data set:
  * `code zowe://ds/lpar1.zosmf/IBMUSER.PDS(IEFBR14)`
* Resource can be opened by clicking URL in browser - for example to open a data set:
  * `<a href="vscode://file/zowe://ds/lpar1.zosmf/IBMUSER.PDS(IEFBR14)">`

Disadvantages:
* Significant effort to refactor tree providers and create extender APIs to work with the `zowe://` scheme
* Extenders that depend on files downloaded by ZE being stored the temp folder can no longer do so

**Comment by VitGottwald** [comment]
Adding @roman-kupriyanov for awareness and discussion.

**Comment by VitGottwald** [comment]
Thank you @t1m0thyj for the propsal! Is the use of `<treeId> ` as server name (authority) intentional?

Passing the example to `vscode.Uri.from`, this is what it returns:

<img width="766" alt="Screenshot 2023-08-04 at 15 05 12" src="https://github.com/zowe/vscode-extension-for-zowe/assets/19686979/78c5c247-4cf5-406d-b7c6-0d8487a69ff2">

**Comment by VitGottwald** [comment]
My second question is how do you intend to represent directories - meaning the list of members of a PDS or a list of datasets with a given prefix, the list of jobs of a given jobname, the list of job outputs for a given jobid?

**Comment by oseam87** [comment]
Would be great to have zopeneditor download the includes of a program to memory instead (could be a configuration). Not sure it is part of this project though.

**Comment by zFernand0** [comment]
Hey @oseam87,
Feel free to open a feature request for the IBM Z Open Editor:
https://github.com/IBM/zopeneditor-about/issues/new/choose

**Comment by JillieBeanSim** [comment]
closing as complete with merge of PR https://github.com/zowe/zowe-explorer-vscode/pull/2777
