### ISSUE TITLE
next: Remove deprecated methods

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2238]
Here is a list of remaining deprecated methods I could find in the `next` branch
- pasteUssFile: `packages/zowe-explorer/src/uss/actions.ts`
- copyDataSet: `packages/zowe-explorer/src/dataset/actions.ts`
- copyUssFile: `packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts`

**Comment by JillieBeanSim** [comment]
changing priority to high with the time for breaking changes in v3 is closing.

**Comment by JTonda** [comment]
Scope limited to the deprecated methods from V1 and V2, not the ones deprecated in the vNext branch.
