### ISSUE TITLE
distinguish the different JES QUEUEs

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2255]
A job can be in 3 states, ie appear in one of the 3 JES QUEUEs: the input QUEUE, the job is not started, the active QUEUE, the job is being executed, the output QUEUE, the job is finished.

- [ ] Investigate the ability to distinguish the different JES QUEUEs.
- [ ] Implementation

**Comment by FALLAI-Denis** [comment]
[JOBS - Enhance management / new Zowe Explorer Extension for JOBS ](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

**Comment by jellypuno** [comment]
Isn't this already implemented in v2.13.1? the Job Status in the filter is working fine

**Comment by likhithanimma1** [comment]
Tested and feature implementation is already in place.

**Comment by likhithanimma1** [comment]
Tested and feature implementation is already in place.
