### ISSUE TITLE
Tabular display option for Jobs tree

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2258]
Zowe Explore uses a hierarchical display of jobs retrieved from the remote z/OS server.
This is not the usual way of working on jobs for z/OS users because whatever software is usually used (IBM SDSF, CA SYSVIEW ...), the jobs are presented in tabular form.
Zowe Explorer should also offer a tabular display of jobs, with the possibility of sorting, filtering, selecting the columns of the properties to display, and triggering actions on the jobs: purge, release, cancel ...

**Comment by FALLAI-Denis** [comment]
[JOBS - Enhance management / new Zowe Explorer Extension for JOBS ](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

**Comment by zFernand0** [comment]
There was a small request during the PI Planning Readouts:
- Make the tabular display extensible
- Investigate implementing in the zFTP extension

**Comment by JillieBeanSim** [comment]
@zFernand0 with completion of this item with the requests brought up during planning this item is growing to the point where it could become it's own Epic.  What do you think?

FYI @adam-wolfe

**Comment by zFernand0** [comment]
Yeah, I think it's a good idea to turn this into an Epic. That way we can track different features (search, filter, actions: purge, cancel, ...) as individual units of work. Same goes for making it extensible and implementing it for the zFTP extension 😋
