### ISSUE TITLE
Search operation does not prompt for login for APIML profile

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2259]
**Steps to Reproduce**
1. Create a team config file with `zowe config auto-init` that contains a z/OSMF profile through APIML. Add a second z/OSMF profile to the config that connects direct to service. See https://github.com/zowe/zowe-cli/issues/1868 for an example of such a config.
2. Delete the `Zowe/secure_config_props` secret from your OS vault so that there are no secure properties stored.
3. Launch Zowe Explorer in the same project directory as the team config file, and click the 🔍 icon in the Data Sets tree for the APIML profile.
![image](https://user-images.githubusercontent.com/22344007/234999785-43c86a22-fc51-4d37-8ee8-2f16f2379ebb.png)

**Actual Behavior**
Two error messages are shown, neither of which tell me how to correct the situation.
![image](https://user-images.githubusercontent.com/22344007/234964163-ede48d01-9dae-4c14-bc1a-c35363cfe634.png)

**Expected Behavior**
When I click the 🔍 icon for the direct-to-service profile, I am prompted to enter username and password.
I would expect the APIML profile to behave similarly and prompt me for credentials to log in to APIML and obtain a token.

**Comment by JillieBeanSim** [comment]
Hey @t1m0thyj I see you are working a draft PR tied to this, also the title & description makes it sound like a bug.
Questions?
1. should this be a bug instead of enhancement?
2. are we planning for it to be included in GA or later?

**Comment by t1m0thyj** [comment]
@JillieBeanSim A bug probably makes sense, and I'm hoping to get a fix included in GA with the draft PR 😋

**Comment by JillieBeanSim** [comment]
Thanks @t1m0thyj I will leave it in the milestone for the GA
