### ISSUE TITLE
Add link to log file

### ISSUE THREAD

**Issue by VitGottwald** [zowe/zowe-explorer-vscode#2271]
**Is your feature request related to a problem? Please describe.**

Latest release of ZOWE Explorer added an output channel, which is great. However, to get a full log, one has to still open the extension directory and manually navigate to the log file.

**Describe the solution you'd like**

Implement the log file button to open ZOWE Explorer log file. Currently this icon is greyed out and cannot be clicked.

**Describe alternatives you've considered**

Open extension folder, go to `log` directory and open the log file from there.

**Comment by VitGottwald** [comment]
<img width="645" alt="Screenshot 2023-05-04 at 16 15 01" src="https://user-images.githubusercontent.com/19686979/236236012-e183105b-9ac2-48f7-9dbb-4e0a66f962f8.png">

**Comment by t1m0thyj** [comment]
It seems this button may have been removed in newer versions of VS Code because I don't see it anymore?
![image](https://github.com/zowe/zowe-explorer-vscode/assets/22344007/080489d0-1c9b-4a0c-9cb3-bebc52ca4942)

**Comment by VitGottwald** [comment]
It is hidden under the three dots and it works 🎉 

<img width="561" alt="image" src="https://github.com/zowe/zowe-explorer-vscode/assets/19686979/29370a5f-4e07-484b-ba38-4071b7c53b20">

As a side note the cog wheel shown on the git output allows setting log level which might also be useful

<img width="620" alt="image" src="https://github.com/zowe/zowe-explorer-vscode/assets/19686979/07e603c5-9d39-4fbc-a55f-4c14de8e1c68">
