### ISSUE TITLE
Double check scopes of settings for correctness

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2303]
some settings that should only be a global setting (application) have workspace setting (window)

**Comment by t1m0thyj** [comment]
The [VS Code docs](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) list all possible values for configuration scope:
> A configuration setting can have one of the following possible scopes:
> 
> * `application` - Settings that apply to all instances of VS Code and can only be configured in user settings.
> * `machine` - Machine specific settings that can be set only in user settings or only in remote settings. For example, an installation path which shouldn't be shared across machines.
> * `machine-overridable` - Machine specific settings that can be overridden by workspace or folder settings.
> * `window` - Windows (instance) specific settings which can be configured in user, workspace, or remote settings.
> * `resource` - Resource settings, which apply to files and folders, and can be configured in all settings levels, even folder settings.
> * `language-overridable` - Resource settings that can be overridable at a language level.
>
> Configuration scopes determine when a setting is available to the user through the Settings editor and whether the setting is applicable. If no `scope` is declared, the default is `window`.

**Comment by JillieBeanSim** [comment]
changing priority to high with the time for breaking changes in v3 is closing.

**Comment by JillieBeanSim** [comment]
Looking into this most of our settings seem to be at the appropriate level.  I tested adding a deprecationMessage to the history settings like below and wonder what the team thinks about this as it will create warnings in the user's settings.json with v3 and our change to internal storage.
<img width="578" alt="Screenshot 2024-06-20 at 8 09 53 AM" src="https://github.com/zowe/zowe-explorer-vscode/assets/49491949/b7139592-742c-497a-9d28-88d4d3b90300">

The `zowe.jobs.confirmSubmission` setting is at `window` but wonder if should be `application` for user only setting/preference? Same with `zowe.commands.alwaysEdit` (commands) & `zowe.jobs.pollInterval`.
Migration, profile, and others that can be different with a project open should stay as `window`.
The `zowe.logger` is set at `window` but wonder if this should be `application` as well with the planned work for adopting VSC logger actions, may need more investigation.

**Comment by zFernand0** [comment]
resolved in https://github.com/zowe/zowe-explorer-vscode/pull/2969
