### ISSUE TITLE
'Remote file has been modified' loop when working with VB recfm

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-explorer-vscode#2327]
**Describe the bug**

I am seeing effectively the same behavior as (https://github.com/zowe/vscode-extension-for-zowe/issues/2007) except now with sequential data sets with a variable blocked record format. I am using an 8-character userid.

**To Reproduce**

1. Open a data set with a VB recfm.
3. Save it.
6. Save it again.
7. Error messages appear saying:

`Failed to save '12345678.TESTVB': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.
`

and

`Remote file has been modified in the meantime. Select 'Compare' to resolve the conflict.`

**Expected behavior**

The user should be able to save and upload the data set without error.

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/122040687/f33eb01b-c365-4008-afbe-b1d3d29bca48)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.8.2
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by adam-wolfe** [comment]
Update: Still experiencing this in 2.14.

**Comment by traeok** [comment]
This was determined to be a z/OS issue. In case any other contributors or developers are encountering this issue on their systems, an APAR was released to resolve this:

https://www.ibm.com/support/pages/apar/PH52243
