### ISSUE TITLE
Need zowe.files.temporaryDownloadsFolder.path setting to be relative to current Workspace

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-explorer-vscode#2368]
**Is your feature request related to a problem? Please describe.**

The path given in the zowe.files.temporaryDownloadsFolder.path setting seems to be necessarily absolute.
This path is used for storing copybooks / includes downloaded from the mainframe (via IBM Z Open Editor).

However, we need to manage different versions of copybooks depending on the Application being modified, and if several VS Code instances are open at the same time, for different contexts, copybooks / includes are common to all Workspaces due to the use of an absolute path.

It is therefore not possible to work on different versions of copybooks / includes at the same time.

**Describe the solution you'd like**

The path declared by zowe.files.temporaryDownloadsFolder.path must be able to be relative to the Workspace, (and probably inside the Workspace, in a dédicated temp folder).

It would even be desirable, if possible, that in the presence of a Workspace associated with a Git Repository, the path depends on the active Git branch, and that a new path be calculated in the event of a Git branch change so as not to risk using copybooks / includes of the wrong version. To do this, you would have to add the Git branch name, for example as a suffix in the calculated path, by eliminating or replacing the forbidden characters to define a path.

See [Separate downloaded copybooks / includes according to Workspace](https://github.com/IBM/zopeneditor-about/issues/350) on `IBM / zopeneditor-about` Github site.

**Comment by FALLAI-Denis** [comment]
Hi,

I tried to use the VS Code variable `${workspaceFolder}` in the path expression for the `zowe.files.temporaryDownloadsFolder.path` parameter, but it didn't work, (in a Windows environment): Zowe Explorer fails to create the temp subfolder in this path.

However according to the VS Code documentation this variable should be resolved and replaced by the corresponding value.
I haven't found a way to debug the reason for the failure in creating the temp subfolder on extension startup.

**Comment by FALLAI-Denis** [comment]
Hi,

Does Zowe Explorer V3 will address this issue?

ZE V3 will manage mainframe resources in memory, (no more temporary directory), so I understand by workspace?

**Comment by traeok** [comment]
Hi @FALLAI-Denis,

That's correct, resources in v3 will be managed by workspace now that they are maintained in-memory. Changes will be periodically detected and propagated to your resources in Zowe Explorer, if they are already saved and in-sync with the mainframe.
