### ISSUE TITLE
USS Filetag is improperly changed to profile-encoding 

### ISSUE THREAD

**Issue by jHeidenberger** [zowe/zowe-explorer-vscode#2377]
**Describe the bug**

I recently (finally) upgraded from v1.8 to version v2.9.1. We work with rocket-git and different encoded uss files (utf-8, ibm-1047, ibm-1141, iso8859-1,...). In the V2 profile I have set "encoding": "1141". If I now e.g. change a utf-8 encoded file, the file tag is changed to IBM-1141 which is not correct and desired. Is there a way to work around changing the filetag? With v1.8 this was possible and the filetags were not changed. <br>
The following options are set for uss: 
_CEE_RUNOPTS=FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) 
_BPXK_AUTOCVT=ALL 

**To Reproduce**

- create a zosmf profile with "encoding: 1141".
- open a utf-encoded uss file by double-clicking for this profile 
- change anything
- save (ctrl-s) the file 

**Expected behavior**

filetag is not changed and uss file is saved with the original filetag (e.g. utf8). 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise 10H21, z/OS 2.5 
- Zowe Explorer Version: v2.9.1
- (Optional) Zowe CLI Version: 7.1.3
- (Optional) Are you using Secure Credential Store? no 

**Additional context**

**Comment by t1m0thyj** [comment]
This may be related to https://github.com/zowe/zowe-cli/issues/1431

When a USS file upload operation is performed, if `encoding` is defined on a "zosmf" profile in zowe.config.json, then it will take precedence over whatever encoding the file is already tagged as.

We could add an option to the z/OS Files SDK to prioritize the file's tagged encoding over the encoding specified in a profile.

**Comment by jHeidenberger** [comment]
Hello, 

thank you for the answer. Your suggestion sounds good and would solve my problem.

**Comment by storgj** [comment]
Hello,
I have also encountered this issue and agree that the desired behaviour should be that the existing tag takes precedence over anything set in the profile.
An option to specify encoding when creating a new USS file would be amazing, but should I open a separate issue for that? As I see it, the zowe cli option to specify the encoding in the profile is only really useful for MVS datasets, whereas I typically need to work with a range of encodings in USS files.

**Comment by JillieBeanSim** [comment]
@t1m0thyj was this resolved with PR https://github.com/zowe/vscode-extension-for-zowe/pull/2594?

**Comment by t1m0thyj** [comment]
> @t1m0thyj was this resolved with PR https://github.com/zowe/vscode-extension-for-zowe/pull/2594?

Yes, this was resolved in that PR because the following line causes tagged encoding to override profile encoding.
https://github.com/zowe/vscode-extension-for-zowe/blob/f1130e7bc1e73773ca37487ff406e620fd5c2e08/packages/zowe-explorer/src/shared/utils.ts#L233

The behavior when saving changes to USS files should be fixed in the next ZE release 2.14.0. However, some actions still use the profile encoding like uploading a local file or copy/pasting files in the USS tree.

> An option to specify encoding when creating a new USS file would be amazing, but should I open a separate issue for that?

@storgj Feel free to open a separate issue specifically for the "Create File" action.
