### ISSUE TITLE
Forward all extra properties to the SDK calls

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2399]
**Is your feature request related to a problem? Please describe.**

With the ability to store any property in your team-config profiles, we would want Zowe Explorer to be able to send those properties to the z/OSMF requests (similar to how the CLI does it).

**Describe the solution you'd like**

A single entrypoint for all SDK calls (ideally exposed to extenders via the zowe-explorer-api) that determines which extra properties need to be sent/forwarded to the corresponding z/OSMF requests

**Describe alternatives you've considered**

Modify every registered command in Zowe Explorer that calls the mainframe in order to pass any extra properties.

---
**Additional Context**

After some discussion in the Zowe Explorer standup (Nov 8th, 2022) we decided to go with the following approach:
- Update the Imperative `ProfileInfo` APIs to return all values in the profile 
  https://github.com/zowe/imperative/issues/899
- Forward all applicable values to the corresponding SDK methods

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1667#issuecomment-1307525441_

**Comment by JillieBeanSim** [comment]
@zFernand0 wasn't this completed on next branch?

**Comment by JillieBeanSim** [comment]
I see the [PR](https://github.com/zowe/zowe-explorer-vscode/pull/2754) where they are all updated to latest needed at the time and all packages seem updated. closing issue

**Comment by zFernand0** [comment]
> I see the [PR](https://github.com/zowe/zowe-explorer-vscode/pull/2754) where they are all updated to latest needed at the time and all packages seem updated. closing issue

That PR definitely helps in this regard (i.e. making it easier to pass any non-schema properties to the corresponding SDKs). We can forward them as needed when/if someone asks for them (for example having a profile with a bunch of dataset allocation attributes like in Step 2 of [Dan's blog](https://medium.com/zowe/tip-how-to-store-zowe-cli-arguments-in-team-config-b96c7d366edc)
