### ISSUE TITLE
Repeated attempt to save member despite S913

### ISSUE THREAD

**Issue by ibmrcruicks** [zowe/zowe-explorer-vscode#2406]
**Description of problem**

**Zowe Extension user edits a read-only dataset, and hits save -- system log shows continual attempts to save the update, despite incurring S913 abends

Results in pages and pages of log entries like:

```
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 605      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00328,0D33,VPWRKD, 606          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 607      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00330,0D33,VPWRKD, 608          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 609      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00332,0D33,VPWRKD, 610          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 611      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00334,0D33,VPWRKD, 612          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 613      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00336,0D33,VPWRKD, 614          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 615      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00338,0D33,VPWRKD, 616          
 ZXP.PUBLIC.JCL(REPRO)                                                      
******************************************************************************
```
with each entry appears 1-3 seconds apart.

**Reproduce Error**

**In VSCode/ZOWE Extension, Open SYS1.MACLIB (be sure you don't have WRITE access!) open ABEND, make arbitrary update, and save (cmd-/ctrl-S, or file->save)**

**Expected behavior**

** Single attempt to write to dataset - note S913 and stop any further attempt to save **

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows and MacOS
- Zowe Explorer Version: 2.9.*
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
Hi @ibmrcruicks ,

Do you have the setting "Files: Auto Save" enabled in VSCode? The auto-save feature might be issuing repeated save requests, even if the previous requests are failing.

Regardless, it sounds like we should try to address this in Zowe Explorer, but this feedback will help clarify the source of the problem.

Thanks!

**Comment by ibmrcruicks** [comment]
not available for the historic events, but I will try and get the user VSCode Autosave setting the next time this shows up.

**Comment by ibmrcruicks** [comment]
finally have a screenshot of a user's VSCode Autosave settings when the S913 loop occured.
![vsc-zowe-autosave](https://github.com/zowe/vscode-extension-for-zowe/assets/25483279/a9770ee1-f3e9-44ff-b605-7015384edab8)

**Comment by ibmrcruicks** [comment]
to try and address the endless S913 abends, and associated SYSLOG flooding, I revoked the TSO account; this then produces

**Comment by traeok** [comment]
Hi @ibmrcruicks, thanks for the update.

Unfortunately, the latest version of Zowe Explorer does not support the "Auto Save" feature. If this feature is enabled, it can cause undefined behavior.

As a temporary workaround, I recommend disabling the "Auto Save" functionality when working within Zowe Explorer. I will discuss the severity/priority of this issue with the squad to determine if we can fix this behavior in v2. This might be resolved in v3 with the implementation of the FileSystemProvider.

**Comment by ibmrcruicks** [comment]
thanks @traeok -- disappointing; when you say the "latest version" does that imply some previous version did/does support AutoSave, or just that it is not supported by Zowe Explorer yet?

Turning off AutoSave affects all the whole VSCode workspace -- what would you recommend as a better afterDelay value?

**Comment by adam-wolfe** [comment]
Related to: https://github.com/zowe/vscode-extension-for-zowe/issues/2627

**Comment by traeok** [comment]
> thanks @traeok -- disappointing; when you say the "latest version" does that imply some previous version did/does support AutoSave, or just that it is not supported by Zowe Explorer yet?
> 
> Turning off AutoSave affects all the VSCode workspaces -- what would you recommend as a better afterDelay value?

@ibmrcruicks I realize my previous reply was a bit vague - from my understanding, Zowe Explorer has never supported the auto-save functionality. 

As for a better `afterDelay` value, it's difficult to recommend a "one-size-fits-all" value since the current behavior can vary depending on network latency, etc. Because of that, I recommend the `onFocusChange` option since it will reduce the amount of save attempts using the auto-save feature. Otherwise, I'd set the delay to at least 2.5 seconds (2500ms) to account for mainframe latency.

We plan to investigate this issue for v2, and I will provide more updates on our resolution as it moves forward.
