### ISSUE TITLE
zowe returning as issue with extension bisect

### ISSUE THREAD

**Issue by lnginyard** [zowe/zowe-explorer-vscode#2434]
Type: <b>Bug</b>

I disabled all downloaded extensions and then manually enabled a couple at a time and performed extension bisect and it returned with zowe.vscode-extension-for-zowe as the issue. Not sure why or the reason but I have the option of reporting it and give the steps to reproduce so thats what I'm doing here. Any help whould be appreciated. 

Extension version: 2.10.0
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 12, 11|
|Memory (System)|16.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id fdd60ec0-9d5a-47d0-90b8-aed724734cd4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by JillieBeanSim** [comment]
Hey @lnginyard thanks for reporting, as before we need steps to reproduce the issue you have seen with Zowe Explorer that led you to run the extension bisect.  Just running the bisect isn't enough there has to be a scenario to test with each extension during the extension bisect to try to recreate an issue.

**Comment by lnginyard** [comment]
Hey @JillieBeanSim and @traeok thanks for your reply and basically informing me about the whole process of extension bisect. I believe I was unaware of what it meant and what to do when performing the procedure. I now realize that Zowe was returning as the issue only because Zowe starts with a Z and since Vs Code extensions are listed in alphabetical order, it shows as the last extension after the bisect or returns as the extension causing the issue because its last in the list. I'm hoping I explained that correctly and in a way that you understand.
