### ISSUE TITLE
The dataset node doesn't refresh after running the migrate or recall action

### ISSUE THREAD

**Issue by patricktiu** [zowe/zowe-explorer-vscode#2448]
**Describe the bug**

After running the `Migrate data set` action against a PDS or SEQ dataset or `Recall data set` action against a migrated dataset, the dataset node icon and context menu items are not refreshed.

**To Reproduce**

1. Right-click a dataset and select 'Migrate data set' action
2. check the context menu items

**Expected behavior**

The dataset icon should be changed to a migrated dataset, and the context menu should be for a migrated dataset.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: v2.10.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
resolved with PR https://github.com/zowe/zowe-explorer-vscode/pull/2765 released in 2.15.0
