### ISSUE TITLE
Issue with credentials not being up to date accross views

### ISSUE THREAD

**Issue by rudyflores** [zowe/zowe-explorer-vscode#2465]
**Describe the bug**

when entering credentials on a profile on a view (let's say DS), if trying to use the same profile on another view, the credential prompt seems to appear again. This gets fixed if the refresh button is pressed though after inserting credentials initially.

**To Reproduce**

1. perform filter search on a profile
2. enter credentials
3. go to the same profile on another view
4. credential prompt should show again

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: 2.11
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JTonda** [comment]
As of 2.16 we are no longer seeing this behavior.  Closing out the issue.
