### ISSUE TITLE
Actual command not found, wanted to execute Zowe.ds.ZoweNode.openPS/153

### ISSUE THREAD

**Issue by nyepiedu** [zowe/zowe-explorer-vscode#2477]
Unable to replicate file contents to host.

**Receive message "Actual command not found, wanted to execute Zowe.ds.ZoweNode.openPS/153"**

Created a new PDS member successfully and data content is being saved correctly on client side.  File is created at host but no data is being replicated to the PDS member at the mainframe.  Install is the Z Xplore mainframe in Dallas.

Mainframe System ID: SOW1   MVS Account: FB3

ZOWE version: 7.18.2

Replication issues seem to happen intermittently.

**Comment by JillieBeanSim** [comment]
Hey @nyepiedu would you have some logs you could share as well as the OS used, Zowe Explorer version and possibly a copy of the error if any showed up while it was trying to upload the data to the new data set.  Thanks

**Comment by t1m0thyj** [comment]
Related to #2124

**Comment by traeok** [comment]
Closing as not planned - related issue #2124 is not planned and this has been resolved in v3.
