### ISSUE TITLE
"Log out of authentication service" and "zowe auth logout apiml" Not working

### ISSUE THREAD

**Issue by Felix-Braun** [zowe/zowe-explorer-vscode#2544]
**Describe the bug**

in VS-Code the "Log out of authentication service" and in the Zowe-CLI "zowe auth logout apiml" are not working
I tried to logout from zowe-explorer, but I got the Error message:

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/c6db1a5b-5ed1-429d-99b4-17b38d35984c)

and in the CLI i tried:

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/44e9700e-c975-44d6-aa30-56f03533abb7)

**To Reproduce**

**Expected behavior**

Able to logout

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.12.0
- (Optional) Zowe CLI Version: 7.18.9
- (Optional) Are you using Secure Credential Store? Yes

**Comment by JillieBeanSim** [comment]
Hey @Felix-Braun thanks for raising the issue.  looking at the 2 different environments the cli takes an extra action removing the info from the config even if it's expired, Zowe Explorer could be updated to follow that scenario as well.
I have a question about the command that succeeds even after logout is successful, does the profile have basic auth or another authentication method stored in the service profile?  I would assume it would fail with the cli command after logout but the call succeeds.

**Comment by Felix-Braun** [comment]
Hey @JillieBeanSim where do I find which auth  I use?

**Comment by Felix-Braun** [comment]
I found it, and yes I'm Using Basic auth

**Comment by traeok** [comment]
Hi @Felix-Braun,

Regarding the original error you encountered: it's possible that when logging out of the authentication service, the token could already be invalid or expired. If Zowe Explorer detects an invalid or expired token, it cancels the logout operation and displays that message. However, this should not prevent you from using other profiles in Zowe Explorer, and you can choose to log in to the authentication service by right-clicking on a profile and selecting "Manage Profile" -> "Log in to authentication service."

I ran some tests but was unable to reproduce the error you encountered. If I log in to API ML from Zowe CLI, I can use the API ML profile in Zowe Explorer until I log out via the "Manage Profile" menu. Conversely, if I log in from Zowe Explorer, I can use the API ML profile until I log out through Zowe CLI. 

If you get the chance, can you please confirm whether your issue has been resolved with the latest version of Zowe Explorer, v2.15.2? Thanks!

**Comment by Felix-Braun** [comment]
Hi, with the new version it works as intended thanks :)
