### ISSUE TITLE
SORT JOBS by DATE is equal to SORT JOBS by JOBID

### ISSUE THREAD

**Issue by Felix-Braun** [zowe/zowe-explorer-vscode#2560]
**Describe the bug**

The sort options sort by DATE SUBMITTED and sort by JOBID are equal.

**To Reproduce**

1. Create job search filter
2. Sort JOBS by JOBID
3. Sort JOBS by DATE SUBMITTED
4. no Difference even

**Expected behavior**

Sort jobs by Datesubmitted

**Desktop (please complete the following information):**

OS: Windows 10
Zowe Explorer Version: 2.12.0
(Optional) Zowe CLI Version: 7.18.9
(Optional) Are you using Secure Credential Store? Yes

**Comment by traeok** [comment]
Hi @Felix-Braun,

To verify, can you confirm what z/OSMF version your LPARs are using? The metadata for the "Date Submitted" option is only returned for LPARs using z/OSMF v2.4 or above. LPARs with a z/OSMF version below v2.4 do not return the required data to sort by submission date.

Also, Job IDs are typically in line with the submitted date, as the job ID increments for every newly submitted job. This isn't always true, such as in cases where the job ID overflows past the maximum number - but when this overflow scenario isn't met, the order of job IDs is generally the same as the order if sorted by submission date.

**Comment by Felix-Braun** [comment]
Hello, we are using z/OSMF v2.4 and I will try, to exceed the maximum number of job IDs and I will get in touch, once I could test this.

**Comment by traeok** [comment]
Hi @Felix-Braun,

Are you still encountering this behavior? The sort feature will fall back to comparing job IDs if the "date submitted" property was not specified on both jobs, but otherwise it will use the `exec-submitted` property from the job response for sorting.

**Comment by traeok** [comment]
Hi @Felix-Braun,

Just following up to verify whether you're still running into this problem. If your LPAR is running z/OSMF version v2.4.0 and above, the `exec-submitted` property will be leveraged for sorting jobs - otherwise, the best that we can do without that metadata is to sort by ID. In most cases, the ID coincides with the submission date, as the ID will increment for each new job that is submitted.

**Comment by Felix-Braun** [comment]
Hi @traeok,

I'm sorry for the late response. No. the problem I encounterted is fixed. 

Thanks
