### ISSUE TITLE
ZOWE JOB Data does not refresh

### ISSUE THREAD

**Issue by Felix-Braun** [zowe/zowe-explorer-vscode#2561]
**Describe the bug**

If I submit a JOB and get the JOBID and then open the unfinished JOB in VS-Code. When the Job is finished I right-click and "refresh Job". But the Job Data doesn't refresh, even if I refresh the Jobs view or the Profile itself, but the Status does. I have to research to get the full job data list.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/d2104cb5-9b49-4f32-b016-94f8afd3fe4a)
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/d5a56bcf-232f-47f4-ad54-af7c2901ba0e)

**Desktop (please complete the following information):**

OS: Windows 10
Zowe Explorer Version: 2.12.1
(Optional) Zowe CLI Version: 7.18.9
(Optional) Are you using Secure Credential Store? Yes

**Comment by JillieBeanSim** [comment]
retested this scenario and it is fixed testing against v2.16.2
@Felix-Braun can you confirm?

**Comment by JillieBeanSim** [comment]
closing as resolved
