### ISSUE TITLE
Use `@vscode/i10n` instead of `vscode-nls` for localization

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2572]
**Is your feature request related to a problem? Please describe.**

The VS Code team is no longer working on new features for `vscode-nls` in favor of `@vscode/i10n`.
They don't plan on discontinuing support for `vscode-nls` at this time, but that may change as `@vscode/i10n` development continues.

**Describe the solution you'd like**

Switch to `@vscode/i10n` for localization in Zowe Explorer.

**Additional context**

This might involve a bit of refactoring to use our localized strings with `@vscode/i10n`, and is also of low priority since `vscode-nls` is still maintained for bug fixes/vulnerabilities.

**Comment by JillieBeanSim** [comment]
closing addressed with https://github.com/zowe/zowe-explorer-vscode/pull/2669
