### ISSUE TITLE
Handle VSCode auto-save functionality

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2579]
If auto-save is enabled in VS Code ("File" -> "Auto Save"), the default behavior is to save every second. Unless users set a longer delay or pick a less aggressive option in the dropdown below, this results in Zowe Explorer continuously issuing new upload requests while a file is being edited (as often as every second if the connection is fast enough).
<img src="https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/63354447-7bf7-4465-9e1a-93ee1a42728e" width="360">

We would like to limit the number of requests that Zowe Explorer makes, so that we don't flood the mainframe with requests and are able to properly handle conflict management without race conditions. Some ideas for how we could handle this:

- Add a warning to our documentation that certain values for the auto-save setting are not recommended for Zowe Explorer users. Perhaps also detect when ZE launches if the auto-save setting is set to save every second, and if so then show a warning that recommends configuring VS Code to auto-save less frequently.
- In v3 if we use a FileSystemProvider (#2207), we should have complete control over the file save and conflict handling operations. This would allow us to ignore save events triggered by auto-save and only handle manual saves, or introduce a new VS Code setting that limits the frequency of ZE upload requests.

**Comment by traeok** [comment]
Closed as completed in #3359 - Auto Save is supported in v3
