### ISSUE TITLE
Cannot switch from basic auth. to token-based auth.

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2590]
**Describe the bug**

_Previously_, a user could access the "Log in to authentication service" option to update a profile to use token-based authentication.

**Now, starting with v2.12.0**: if a user has basic authentication configured for a specific profile, that profile cannot be updated to token-based auth. using Zowe Explorer. This is because the "Manage Profile" feature hides certain options based on the profile's current authentication type.

**To Reproduce**

- Configure a profile so that it uses basic authentication and secure props (user/password)
- Right-click on the profile -> select "Manage Profile"
- Notice that there is no longer an option to log in using an authentication service

**Expected behavior**

The "Log in to authentication service" option should still be accessible when managing profiles that use basic authentication.
If necessary, we can warn the user that they are switching their authentication type if trying to switch from token-based -> basic, or vice versa.

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: latest on `main` (2.12.2)
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

One workaround is to remove the `user` and `password` props from the `secure` array in the Zowe config, but this is not generally recommended.

**Comment by t1m0thyj** [comment]
The opposite is also true - cannot switch from token auth to basic auth, unless you add a secure array containing "user" and "password" to the profile you want to use basic auth for.

**Comment by t1m0thyj** [comment]
We have a way to clear the secure array using Imperative's low-level Config API:
```
const profName = "base";
const profAttrs = profCache.getProfileFromConfig(profName);
const configApi = (await profCache.getProfileInfo()).getTeamConfig();
configApi.set(`${profAttrs.profLoc.jsonLoc}.secure`, []);
configApi.save();
```

This requires that you know the name of the profile where the secure array is located. Perhaps it would be more convenient for us to add a method to the ProfileInfo API that given a profile name, can find the service or base profile where the secure array is located and clear it?

**Comment by zFernand0** [comment]
> Perhaps it would be more convenient for us to add a method to the ProfileInfo API that given a profile name, can find the service or base profile where the secure array is located and clear it?

FWIW, I kind of agree with this 😋
