### ISSUE TITLE
Update ZE to use imperative's APIs for updating imperative.json 

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2622]
imperative has been creating APIs for reading and editing the imperative.json file credentialManager information.  We need to adopt the full use of these APIs and no longer edit the file without the APIs.

**Comment by JTonda** [comment]
Plan to allow for boolean and string properties.

**Comment by zFernand0** [comment]
Will be fixed in: 
- #2994
