### ISSUE TITLE
Log out from API ML is not available anymore with Manage Profile menu

### ISSUE THREAD

**Issue by roman-kupriyanov** [zowe/zowe-explorer-vscode#2633]
**Describe the bug**

After using the "Manage Profile -> Log in to authentication service" option for the z/OSMF type of the profile and successful login, the "Log out" option does not appear anymore after the introduction of "Manage Profile" menu.

**To Reproduce**

1. Right click on the API ML type of profile in the Zowe Explorer Data Sets / USS / Jobs view (for me - "zosmf-apiml")
2. Select "Manage Profile".
3. Use "Log in to authentication service" item.
4. After login is successful, return to "Manage Profile" menu for the same profile and notice that only "Log in" is still available and not "Log out" (see screenshot below).

**Expected behavior**

After successful login to API ML using Zowe Explorer, it is expected to be able to logout using ZE too. For now the only way is to use Zowe CLI for that.

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/91762867/8f1b389a-7ed4-4557-9c53-d806349dfde7)

**Desktop:**

- OS: macOS 14.2
- Zowe Explorer Version: 2.13.0
- Zowe CLI Version: 7.18.8
- Are you using Secure Credential Store? Yes

**Additional info**

Base profile in the Team config:

```json
"base": {
            "type": "base",
            "properties": {
                "host": "apiml.services.net",
                "protocol": "https",
                "port": 60080,
                "rejectUnauthorized": true,
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "tokenValue"
            ]
        },
```

Actual z/OSMF profile:

```json
"zosmf-apiml": {
    "type": "zosmf",
    "properties": {
        "basePath": "/ibmzosmf/api/v1"
    }
}
```

**Comment by JillieBeanSim** [comment]
This was resolved with PR https://github.com/zowe/vscode-extension-for-zowe/pull/2639 and will be included in an upcoming release

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/d2a16a2d-5bee-4b36-8162-7f99dccb2f74

**Comment by adam-wolfe** [comment]
After some more trial and error, I have been able to recreate this. It may be related to https://github.com/zowe/vscode-extension-for-zowe/issues/2637.

Here is my config:

```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "zosmf": {
            "type": "zosmf",
            "properties": {
                "port": [zosmf direct port]
            },
            "secure": [
                "user",
                "password"
            ]
        },
        "zosmf-apiml": {
            "type": "zosmf",
            "properties": {
                "basePath": [api base path]
            }
        },
        "base": {
            "type": "base",
            "properties": {
                "host": [host name],
                "protocol": "https",
                "port": [apiml port],
                "rejectUnauthorized": true,
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "tokenValue"
            ]
        }
    },
    "defaults": {
        "zosmf": "zosmf",
        "base": "base"
    },
    "autoStore": true
}
```
If you delete the secure array from the 'zosmf' profile, the Manage Profiles menu for 'zosmf-apiml' returns to normal.

**Comment by roman-kupriyanov** [comment]
Hello, seems I have this issue appeared again.

- OS: macOS 14.4.1
- Zowe Explorer Version: 2.15.4
- Zowe CLI Version: 7.24.2
- Are you using Secure Credential Store? Yes

This time I use `~/.zowe/zowe.config.user.json` to override some profile parameters in my `~/.zowe/zowe.config.json`.

`~/.zowe/zowe.config.user.json`:

```json
{
  "$schema": "./zowe.schema.json",
  "profiles": {
    "mfts": {
      "properties": {
        "ccid": "TEST",
        "comment": "Changes by ME"
      },
      "profiles": {
        "demobox": {
          "type": "endevor-location",
          "properties": {
            "subsystem": "DEMOBOX"
          },
          "secure": []
        },
        "my-sandbox": {
          "type": "endevor-location",
          "properties": {
            "subsystem": "MYBOX"
          },
          "secure": []
        }
      }
    },
    "mfne": {
      "properties": {
        "instance": "MFNE",
        "type": "*",
        "ccid": "TEST",
        "comment": "Changes by ME"
      },
      "profiles": {
        "other-sandbox": {
          "type": "endevor-location",
          "properties": {
            "environment": "DEV",
            "stageNumber": "1",
            "system": "SYSTEST",
            "subsystem": "SBSTEST"
          },
          "secure": []
        }
      }
    }
  },
  "defaults": {
    "endevor-location": "mfts.my-sandbox"
  }
}
```

`.zowe/zowe.config.json`:

```json
{
  "$schema": "./zowe.schema.json",
  "profiles": {
    "base": {
      "type": "base",
      "properties": {
        "host": "apiml.services.net",
        "protocol": "https",
        "port": 60608,
        "rejectUnauthorized": true,
        "tokenType": "apimlAuthenticationToken"
      },
      "secure": ["tokenValue"]
    },
    "my-mf": {
      "profiles": {
        "zosmf": {
          "type": "zosmf",
          "properties": {
            "port": 1443
          },
          "secure": []
        },
        "zosmf-apiml": {
          "type": "zosmf",
          "properties": {
            "basePath": "/ibmzosmf/api/v1"
          }
        },
        "endevor-apiml": {
          "type": "endevor",
          "properties": {
            "basePath": "/caendevorapi/api/v2"
          }
        }
      }
    },
    "mfts": {
      "properties": {
        "environment": "DEV",
        "instance": "MFTS",
        "system": "SYSPROD",
        "stageNumber": "1",
        "type": "*"
      },
      "profiles": {
        "app-hotfixes": {
          "type": "endevor-location",
          "properties": {
            "environment": "QA",
            "subsystem": "SYSPROD"
          },
          "secure": []
        },
      }
    },
  },
  "defaults": {
    "base": "base",
    "endevor": "my-mf.endevor-apiml",
    "endevor-location": "mfts.app-hotfixes",
    "zosmf": "my-mf.zosmf-apiml"
  },
  "autoStore": true
}
```

After the API ML successful login using "Manage profile" menu on `my-mf.zosmf-apiml` profile (`tokenType` and `tokenValue` appears in the `base` profile in the `zowe.config.json` file), I still cannot see the logout option:

![image](https://github.com/zowe/zowe-explorer-vscode/assets/91762867/9dc59c5a-993d-403a-b682-3a249f0933bc)

Can confirm though if I remove the User config everything works as expected and the logout option is in place.

**Comment by t1m0thyj** [comment]
@roman-kupriyanov Thanks for reporting this! We have found the underlying issue lies in Imperative. I've opened https://github.com/zowe/zowe-cli/pull/2135 to fix it there. Once it is merged we'll update the Imperative dependency in Zowe Explorer 🙂
