### ISSUE TITLE
feat(unix-cmd): User Experience improvements

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2643]
**Is your feature request related to a problem? Please describe.**

There were some unexpected error messages when using the `Issue Unix Command` functionality.

- [ ] When no search path was entered, we get an error 
    - ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/2cccc3e9-b653-4c0d-9c65-8962494217fb)
- [ ] When reviewing the history (terminal output), it would be nice to know which user and/or ssh-profile used to run the command
    - ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/c5fecf26-5bf6-4766-97f3-74f401319282)
- [ ] When using it from the command palette, errors are not displayed if something goes wrong (no ssh profile, no username)
- [ ] When there are no ssh profiles, nothing happens
- [ ] When the ssh profile does not have user or password, we get an invalid username instead of being prompted for it
    - ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/35ad752c-a6d0-4496-a3b7-5c047339295b)

**Describe the solution you'd like**

These are the solutions I've considered for each item:
- _When no search path was entered..._
  - To be prompted for a path, even though it does not trigger a search (similar to using the Issue Unix Command function from the command palette)
- _When reviewing the history (terminal output)..._
  - To have the user and/or profile used to run the command
    ```
    CUST009 @ ssh-profile-1 : /u/users/cust009 > ls -al

    ...output...
    ```
- _When using it from the command palette..._
  -  To display a message when no ssh profile is present, or be prompted for credentials.
- _When there are no ssh profiles..._
  - To display a message when no ssh profile is present.
- _When the ssh profile does not have user or password..._
  - To be prompted for credentials 😋 

**Describe alternatives you've considered**

N/A

**Additional context**

Tested while reviewing:
- #2626

**Comment by JillieBeanSim** [comment]
for clarification on the last expected behavior with credentials @zFernand0, do we plan to store these credentials?  Also, shouldn't it respect the base profile information is sharing host & other info but will also need to be using basic auth and not tokens to work with ssh profile.  How is this handled by the CLI/imperative?
