### ISSUE TITLE
Not handling cancelling upload to unix directory

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2674]
**Describe the bug**

error shown when cancel selected in upload to uss instead of operation cancelled message 
<img width="465" alt="Screenshot 2024-01-22 at 12 54 20 PM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/bdc0d02a-4de7-4d9d-8d41-5e8fdfa95a50">

**To Reproduce**

1. Go to USS tree and enter filter search
2. Click on directory and select upload file
3. Click cancel in upload dialog box

**Expected behavior**

no error, just message seen in other cases like `Operation cancelled`

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: main 2.14.0 but pre-existing 
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by adam-wolfe** [comment]
This issue is resolved in 2.16.0 and in the next branch.
