### ISSUE TITLE
Profile validation assumes token auth for profile using basic auth

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2682]
**Describe the bug**

In some cases when issuing a filter prompt for a profile that uses basic auth, profile validation is performed for the wrong profile (a different one that uses token auth).

**To Reproduce**

1. Create a project team config with a zosmf (apiml) profile and base profile using token auth
2. Log in to authentication service and wait for token to expire
3. Create a global team config with a zosmf (direct to service) profile and base profile using basic auth
4. Ensure user/password are stored for the 2nd base profile
5. Issue a USS search for the direct to service zosmf profile
6. See a popup requesting to "log in to authentication service"

**Expected behavior**

The default base profile using token auth in project team config should not have any effect on global team config which contains an identically named base profile using basic auth

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/ca231b4c-108f-453e-8418-bef3b74f4e88)

**Desktop (please complete the following information):**

- OS: MacOS 14.3
- Zowe Explorer Version: 2.14.0

**Additional context**

**Comment by JTonda** [comment]
Workaround:  Rename the project base profile.

Note:
Possibility of having the zowe config init to use a different name (projectBase).  Make sure that this also applies to the profile info apis.

**Comment by t1m0thyj** [comment]
The enhancement to rename base profiles has been made in Zowe SDKs: https://github.com/zowe/zowe-cli/pull/2194

Before the ZE V3 release, we'll update our SDK deps to benefit from this enhancement

**Comment by awharn** [comment]
> The enhancement to rename base profiles has been made in Zowe SDKs: [zowe/zowe-cli#2194](https://github.com/zowe/zowe-cli/pull/2194)
> 
> Before the ZE V3 release, we'll need to update our SDK deps to benefit from this enhancement

Completed in #3020 and #2994
