### ISSUE TITLE
Data set members may fail to open in binary mode

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2696]
Data set members cannot always be opened in binary mode depending on the contents.

The following member can be opened in binary mode (as long as there is no trailing line) because it is exactly 80 bytes long:
```
Hello World                                                                    $
```

Attempting to open the following member in binary mode results in an error:
```
Hello World $
```
<img width="460" src="https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/5484f1c6-5408-4e3b-a59a-d8f1dae45bd1">

Here are the attributes of the PDS:
<img width="360" src="https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/1065da7c-f928-49e3-8eff-c9d363304040">

**Comment by adam-wolfe** [comment]
Also running into this issue with allocation settings:
![image](https://github.com/zowe/zowe-explorer-vscode/assets/122040687/0cce53cb-f5ea-4179-91bd-fbf79001dd48)

**Comment by t1m0thyj** [comment]
Discussed with @awharn and realized we could probably reuse some of the logic for opening USS nodes, to catch an error when opening a data set and fall back to binary mode: https://github.com/zowe/zowe-explorer-vscode/blob/main/packages/zowe-explorer/src/uss/ZoweUSSNode.ts#L624
