### ISSUE TITLE
Unable to open favorited job search

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2751]
**Describe the bug**

Seeing this error when opening a favorited search
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/d178840e-0fca-4fd4-bd68-3df83970b3d4)

**To Reproduce**

1. Save a job search
2. try to open it
3. ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/056ed3c3-63c6-40b3-8641-b77cd82b18f9)

**Expected behavior**

Either to open in the existing profile, or be able to browse the job

**Desktop (please complete the following information):**

- OS: Ubuntu
- Zowe Explorer Version:  vNext
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

**Comment by traeok** [comment]
This could be coming from one of the functions that we use to recreate favorite nodes during startup.
Here are a couple that come to mind:

- `initializeFavorites`
- `initializeFavChildNodeForProfile`

**Comment by zFernand0** [comment]
This also happens on 2.14.1.
However, the search works just fine 😋 

It'd be nice not to see the error message though 😅
