### ISSUE TITLE
Strange behavior when running SSH command if credentials are not yet stored

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2762]
To reproduce the issue:
* Have a Zowe client config (`zowe.config.json`) with a zosmf and ssh profile
* Delete secure credentials (`Zowe/secure_config_props`) from the vault so you'll be prompted for them

**Actual Behavior**
1. Right-click on the zosmf profile in the USS tree and select "Issue Unix Command". Notice that nothing happens.
2. Or select "Issue Unix Command" from the command palette. After being prompted for a zosmf and ssh profile, then I am prompted to enter credentials twice. 

**Expected Behavior**
1. When right-clicking on a zosmf profile in the USS tree, I should be prompted for an ssh profile to use.
2. If credentials are not yet stored, I should be prompted only once for user/password and they should be stored in the zosmf profile.

**Comment by zFernand0** [comment]
- Fixed by #3084
