### ISSUE TITLE
Warn users that v1 profiles are going away soon

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2763]
**Is your feature request related to a problem? Please describe.**

Users of Zowe Explorer v2 who have not yet migrated to team config may not be aware of the impending need to do so.

**Describe the solution you'd like**

Show a warning message when Zowe Explorer activates which mentions that support for v1 profiles will end shortly. The message could show 2 buttons, "Convert" to migrate v1 profiles to team config and "Don't show this again" so we don't annoy people.

**Describe alternatives you've considered**

We could not warn users at all beforehand, but this might result in a number of unhappy users filing bug reports after VS Code auto-updates ZE to v3. Even with a conversion tool built-in to v3 that migrates v1 profiles to team config, users may be surprised if their old profiles suddenly don't work anymore.

**Additional context**

We should maybe wait to add the warning until we have a definite GA date planned for Zowe v3.

**Comment by JillieBeanSim** [comment]
Hey @t1m0thyj can this be closed as the GA is pretty close now?
