### ISSUE TITLE
zowe-explorer-api's IApiRegisterClient.onProfilesUpdate() does not fire when credentials are updated

### ISSUE THREAD

**Issue by FrankSu1996** [zowe/zowe-explorer-vscode#2822]
when registering a listener to IApiRegisterClient.onProfilesUpdate(), updating credentials that are securely stored does not fire the EventTypes.UPDATE event.

**Expected behavior**

As updating credentials is modifying the profile attributes, expect to see the console.log(). However, nothing happens. onProfilesUpdate(e) is never hit when setting a breakpoint inside

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Zowe Explorer Version: zowe-explorer-api 2.15.2
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by rudyflores** [comment]
Related to #2546 and https://github.com/zowe/zowe-cli/issues/1987

**Comment by traeok** [comment]
Hi @FrankSu1996,

I just wanted to ask some clarifying questions on this issue before we look into a resolution:

1. Are the credentials being updated within Zowe Explorer or the extender? Or does the credential update occur from outside of Zowe Explorer?
2. Have you experienced this behavior with the `onProfilesUpdate` in previous API versions?

Thanks!

**Comment by FrankSu1996** [comment]
Sorry, never saw your questions before. 

1. It seems to happen almost 100% of the time when using the ZE manage profile action to update credentials. Using our extender, sometimes it fires, and other times it doesn't. I have noticed it tends to fire when user/password isn't already defined in our service profile, or the base profile. If it is already defined, then even from our extender, the onProfilesUpdate also will not fire. Note that our extender ultimately calls the same ProfileInfo.updateProperty() as ZE does to update credentials.

2. We only started trying onProfilesUpdate with 2.15.2. The problem still persists in 2.16.0

**Comment by traeok** [comment]
Hi @FrankSu1996,

Thanks for providing the context for how the credentials are updated. Although we have logic in place that watches for changes to the config file, the mentioned scenario does not change the contents of the config. I've added a check that will fire the event when:
* credentials are updated
* the user is using secure credentials in Zowe Explorer

There is one side effect that I can think of from this change, which is that the event will fire twice when the user adds secure credentials to a profile for the first time (once from the file system watcher, and the second time from this added check). Would this be considered problematic from your extension's point of view?

**Comment by FrankSu1996** [comment]
It wouldn't be detrimental; we currently use a VsCode file watcher for update events as a workaround, and I've noticed it sometimes fires twice as well. To handle this we debounce the callback in response to the update events. I think the most important thing for us is to ensure that we always have the most up to date contents of the zowe-explorer-api's ProfilesCache, so this would still beneficial.

**Comment by FrankSu1996** [comment]
Just to confirm, the onProfilesUpdate() will still fire if _any_ secure values are updated right, not just credentials?

**Comment by traeok** [comment]
> Just to confirm, the onProfilesUpdate() will still fire if _any_ secure values are updated right, not just credentials?

It depends on how the secure value is updated. Currently, we do not have the capability to check for secure value updates outside of Zowe Explorer. We will be able to support vault updates outside of Zowe Explorer once the event emitter is fully implemented in Imperative. In the meantime, we can fire this event whenever secure values are updated within Zowe Explorer itself.

The linked pull request specifically resolves the described scenario (where the event is not fired after user updates secure credentials on a profile using "Manage Profile" -> "Update Credentials"). I'll add another check to handle logging in/out of an authentication service, but the best we can do for now is fire this event whenever Zowe Explorer has changed the secure values.

**Comment by FrankSu1996** [comment]
Thanks for the clarification. Our extender does update secure values to our own service profiles, using both ProfileInfo.updateProperty() and Config.set() (to handle an edge case). We do make sure that we are using the instances from zowe-explorer-api to do this though. It’s good that imperative is implementing their own proper listener mechanism. This has been something on our wish list for them to provide. 

Ultimately, we need so ensure proper consistency and isolation in read/writes to service profile objects from imperative. Although I understand that their market direction is to allow users to directly edit team config files, I still think data persistence needs to be backed by a proper db like SQLlite. For example, currently, imperative does not provide any sort of unique ID service profiles, which is required to form relationships between profiles and other business logic objects. We currently are forced to implement workarounds to inject uuids on our service profile, but really stuff like this should be provided by their API. As far as I can tell from the source code, there also is no file locking when read/writing to the config files, so there are inherent race conditions that can occur between different Zowe Applications/extenders.

**Comment by JillieBeanSim** [comment]
closing issue for the 2.16.2 milestone completion, thanks @traeok  for creating to port to next PR
