### ISSUE TITLE
zFTP: Spool files are not listed properly for active jobs

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2832]
**Describe the bug**

Related: https://github.com/zowe/zowe-cli-ftp-plugin/issues/156

Spool files are not listed properly for active jobs using a zFTP profile. This applies to both v2 and v3.
This is a limitation in `zos-node-accessor`: https://github.com/IBM/zos-node-accessor/blob/60cdfd26eea001686d50a92128f12a6fff0f91ca/lib/zosAccessor.js#L867-L868

**To Reproduce**

- Try to expand a job that's active under a zFTP profile
- Notice that there is only one spool file listed, named `[(0)]`, and it has no information
- Opening said file results in an editor tab named `0` to appear with no contents

**Expected behavior**

We should either:
- show a placeholder node to say that FTP profiles do not support listing spool files for active jobs
- not show any spool files

I prefer the first option because it provides context for the failure when listing spool files.

**Screenshots**

![image](https://github.com/zowe/zowe-explorer-vscode/assets/86500639/1399492d-1f0b-457b-917a-908ace9e2458)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: v2.15.2

**Comment by traeok** [comment]
@JillieBeanSim suggested that we should catch any errors from the extender and then handle those errors accordingly in Zowe Explorer. In hindsight, I prefer this option over the above solutions mentioned, because it is consistent with our expectations for extenders to handle errors where applicable.

**Comment by JillieBeanSim** [comment]
closing with merge of linked PR
