### ISSUE TITLE
New PDS Member Node Does Not Open Unless Pull from Mainframe

### ISSUE THREAD

**Issue by awharn** [zowe/zowe-explorer-vscode#2857]
**Describe the bug**

After creating a new member on a PDS, the file opens for edit. If that tab is closed, the member cannot be opened again unless you pull from mainframe

**To Reproduce**
1. Create new PDS Member
2. Close the editor
3. Attempt to open the PDS member again

**Expected behavior**

The PDS member would open

**Screenshots**
![Peek 2024-04-16 14-14](https://github.com/zowe/zowe-explorer-vscode/assets/53578529/8ab1d728-d421-4cea-845c-46d53b77a7dd)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Zowe Explorer Version: 2.15.2
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

**Comment by traeok** [comment]
Note: 

This seems related to the command that's assigned to the new node. Does the new member have the right command assigned to it (or any command at all)?
