### ISSUE TITLE
Saving favorited data sets without searching them explicitly results in an error

### ISSUE THREAD

**Issue by gourmsen** [zowe/zowe-explorer-vscode#2880]
**Describe the bug**

When opening a data set (or member) from the favorites bar, they can't be saved - this results in a TypeScript error. When explicitly searching for them in the profile, they can suddenly be saved. After searching for something else again, saving them results in the mentioned error again. It is worth mentioning that when you have searched for a PDS and a member of that PDS is open, you also can't save it until you've opened the PDS in the tree view.

**To Reproduce**

1. Open data set (or member of a PDS) from favorites
2. Try to save it with `Ctrl + S` (displays error)
3. Search for it explicitly (so it is in the tree view - for members, expand the PDS)
4. Try to save it (works normally)

**Expected behavior**

Regardless, of whether or not the data set has been explicitly searched for, saving it should be possible.

**Screenshots**

![Screenshot 2024-04-25 104848](https://github.com/zowe/zowe-explorer-vscode/assets/2014448/77df0b5b-4951-4720-a53d-95f9848135f9)

![image](https://github.com/zowe/zowe-explorer-vscode/assets/2014448/7b846012-ee48-4a1e-b904-ef3119f88e2f)

**Desktop (please complete the following information):**

- OS: Windows 11 Pro 23H2
- Zowe Explorer Version: 2.15.4
- Zowe CLI Version: 7.24.0

**Additional context**

I've experienced this bug at the same time as #2873. It might be tied together in some way.

**Comment by paulobigas** [comment]
I also confirm the bug

**Comment by t1m0thyj** [comment]
Do you have a custom temporary folder configured for Zowe Explorer in VS Code settings?

<img width="457" alt="image" src="https://github.com/zowe/zowe-explorer-vscode/assets/22344007/33f4ffda-3eb7-47aa-ae85-baff5b9deb02">

If so, changing the drive letter to be lowercase should fix the problem:

<img width="457" alt="image" src="https://github.com/zowe/zowe-explorer-vscode/assets/22344007/3909b5a8-baea-471b-ac41-52e062d858cd">

We are working on a fix in #2885 to support uppercase drive letters in the temp path.

**Comment by gourmsen** [comment]
Thank you! Yes, I do and this fixed the problem on my machine.
