### ISSUE TITLE
v3 - Should handle SSH profile credentials vs throw error

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2901]
**Describe the bug**

Error received with outdated SSH credentials stored securely in SSH profile, only way to update these values atm is via cli command.  We will need to address this to stay independent from an install stand point.

<img width="480" alt="Screenshot 2024-05-03 at 9 06 51 AM" src="https://github.com/zowe/zowe-explorer-vscode/assets/49491949/f0c93cc1-e787-49c5-9775-188349df1093">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: [v3 latest pre-release](https://github.com/zowe/zowe-explorer-vscode/releases/tag/v3.0.0-next.202404242037)
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by likhithanimma1** [comment]
Fixed by https://github.com/zowe/zowe-explorer-vscode/pull/3098
