### ISSUE TITLE
Updating credentials empties all tree views in the Activity Bar

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2906]
**Describe the bug**

In the latest version of Zowe Explorer, updating credentials on a profile causes all of the profile nodes to disappear from the tree view.

The only workaround I've found thus far is to reload the window (hence, restarting VS Code also works). If I try to add a profile back to the tree prior to doing so, nothing happens.

**To Reproduce**

1. Right-click on a profile node in the tree view
2. Select "Manage Profile" -> "Update Credentials"
3. Type in the new credentials for the profile
4. Notice that after entering the password and pressing the 'Enter' key, the "credential update" message shows, but all of the profiles have been removed from the tree

**Expected behavior**

Profiles should not be removed from the tree view after updating credentials for a specific profile.

**Screenshots**

![ZE-Update-Creds-Bug](https://github.com/zowe/zowe-explorer-vscode/assets/86500639/a15cc070-bf3a-451c-8d0e-18d0a56b5b62)

**Desktop (please complete the following information):**

- OS: Windows 10 22H2
- Zowe Explorer Version: 2.15.4
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? Yes

**Comment by t1m0thyj** [comment]
@awharn and I see the same behavior in ZE V3 where tree views are emptied when a new team config is created.

The issue may be related to the log channel closing and failing to re-open when the `extRefresh` command runs.
