### ISSUE TITLE
Regression on: fix(ProfilesCache): Clear object caches before refresh #2795

### ISSUE THREAD

**Issue by FrankSu1996** [zowe/zowe-explorer-vscode#2910]
**Describe the bug**

Issue #2795 seems to have regressed. When the fix came out in v2.15.2, I tested it and it worked. Today, I stumbled across the behavior again, where removing the single instance of our profile type still caused the ProfilesCache to hold onto the stale reference. The only other thing that has changed in my VsCode environment that I could think of is the zowe-explorer version and VsCode version.

**To Reproduce**

1. Contribute new profile type using zowe-explorer-api.
2. Create a team config file. Doesn't matter if it's global/project
3. Delete the single instance of the contributed profile, and call ProfilesCache.refresh()

**Expected behavior**

ProfilesCache should correctly remove the profile. But it doesn't.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- zowe-explorer-api version: 2.15.2, also tried with latest 2.15.3
- zowe-explorer version: 2.15.4
- VsCode version: 1.89.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store? yes

**Comment by t1m0thyj** [comment]
This may be related to #2888

**Comment by JillieBeanSim** [comment]
closing with merge of attched PR

**Comment by FrankSu1996** [comment]
Just tested using v2.16.0, the issue persists for both global/project level config files
