### ISSUE TITLE
Vnext version 3.0 of Zowe Explorer uses a non-existent API

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-explorer-vscode#2918]
**Describe the bug**

I noticed that in the next branch of ZE, the file zowe-explorer-vscode/packages/zowe-explorer-api/src/profiles
/ProfilesCache.ts uses the function `imperative.ConfigBuilder.convert`.

The function imperative.ConfigBuilder.convert no longer exists in the next branch of the Zowe CLI SDK. I suspect that the ZE team used an older snapshot of the CLI vNext SDK, and has not yet updated to use a newer snapshot.

I think that once ZE uses a newer CLI SDK version, ZE will not even compile. ZE code will have to be refactored to use a new CLI SDK function and interfaces before ZE will work again.

I open this issue so that the ZE team is aware of failures that will likely occur after they perform a routine update to a newer version of the CLI SDK.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JTonda** [comment]
This will have to be addressed when we update our cli sdks.
