### ISSUE TITLE
Compile a list of V3 breaking changes for users and extenders

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-explorer-vscode#2929]
**Is your feature request related to a problem? Please describe.**

The Onboarding Squad has requested that all squads produce a list of breaking changes for V3. A document exists that covers breaking changes for Zowe CLI and the Client Node.js SDKs and is available here: https://ibm.box.com/s/9h18h0blwl0yrtxcyeh1i0am70vdlcs5 in the V3 folder on box: https://broadcom.ent.box.com/folder/228322599725

**Describe the solution you'd like**

The Zowe Explorer Squad should assemble something for Zowe Explorer and the Zowe Explorer APIs similar to what the CLI Squad has done.

**Describe alternatives you've considered**

**Additional context**

**Comment by adam-wolfe** [comment]
It looks like https://github.com/zowe/zowe-explorer-vscode/wiki/v3-Changes-for-Users-and-Extenders is already being used for this purpose.

**Comment by t1m0thyj** [comment]
Created a breaking changes document on Box: https://ibm.box.com/s/64d0kzjwretss39xghb95r4bximgab7u

@adam-wolfe @JillieBeanSim Seems like we have 3 places for tracking V3 changes now, should we standardize on one going forward?
* [Extenders.md](https://github.com/zowe/zowe-explorer-vscode/blob/next/docs/early-access/v3/Extenders.md)
* [ZE wiki](https://github.com/zowe/zowe-explorer-vscode/wiki/v3-Changes-for-Users-and-Extenders)
* The Box document

**Comment by t1m0thyj** [comment]
Discussed this at standup and I believe the plan is to keep the Box document up-to-date with any changes made to Extender.md, since all Zowe squads have been requested to create a Box document that details their V3 breaking changes 🙂 

@adam-wolfe has opened a PR to add the links to zowe.org: https://github.com/zowe/zowe.github.io/pull/924
