### ISSUE TITLE
Port recent pull requests from v2 to vNext

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2936]
Below is a list of PRs that may need to be ported to vNext - if you are tagged, please either open a PR to port the changes, or comment below if the PR has already been ported or doesn't need to be 🙂 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2776 @rudyflores 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2801 @t1m0thyj 
* [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/2804 @SanthoshiBoyina~
  * Unable to reproduce. Thanks @SanthoshiBoyina1
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2765 @likhithanimma1  
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2816 @JillieBeanSim 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2810 @rudyflores 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2853 @traeok 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2838 @t1m0thyj 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2848 @likhithanimma1 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2860 @traeok 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2872 @t1m0thyj 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2865 @JillieBeanSim 
* [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/2820 @t1m0thyj~
  * Not applicable to vNext because FileSystemProvider replaced old save logic
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2869 @JillieBeanSim 
* [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/2885 @t1m0thyj~
  * Not applicable to vNext because temp folder setting will be removed soon:
    https://github.com/zowe/zowe-explorer-vscode/issues/2951
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2802 @t1m0thyj 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2908 @traeok 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2917 @t1m0thyj 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2919 @t1m0thyj 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2942 @likhithanimma1 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2943 @t1m0thyj 
* [x] https://github.com/zowe/zowe-explorer-vscode/pull/2948 @traeok

**Comment by traeok** [comment]
I've removed #2874 from this list as the issue does not occur in v3 😋

**Comment by JillieBeanSim** [comment]
PR for items tagged jilliebeansimm
https://github.com/zowe/zowe-explorer-vscode/pull/2945

**Comment by SanthoshiBoyina1** [comment]
https://github.com/zowe/zowe-explorer-vscode/pull/2804 not able to recreate this issue on Next branch. It may not need porting.

**Comment by traeok** [comment]
Are we good to close this out? Looks like all of the PRs listed above have been ported to v3.
