### ISSUE TITLE
Remote lookup functionality for URIs that do not yet exist

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2938]
**Is your feature request related to a problem? Please describe.**

Currently, the resource URIs for v3 only point to resources that were added to the provider by a tree view action. If no actions are performed in the tree view, but a user tries to access a URI through something like a Virtual Workspace, then the URI lookup will fail until the entry is added to the provider.

**Describe the solution you'd like**

Fallback to a remote lookup of the URI if the entry is not yet present in the file system.

**Describe alternatives you've considered**

You can navigate to a directory or filter pattern in the tree view to get the entries to populate, but this is not convenient for developers that want to leverage resource URIs outside the tree view.

**Comment by zFernand0** [comment]
Should we define virtualWorkspaces as a capability when addressing these limitations?
- https://code.visualstudio.com/api/extension-guides/virtual-workspaces#partial-and-full-support-for-virtual-workspaces

**Comment by JillieBeanSim** [comment]
closing as attached PR is merged
