### ISSUE TITLE
Some PDS members open with empty contents when initially accessed

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2940]
**Describe the bug**

Sometimes a PDS member will open without any contents upon initial access. This behavior is not consistent as other members can be opened without issue.

**To Reproduce**

TBD

**Expected behavior**

The PDS member should open with its contents populated in the editor for the first access.

**Comment by t1m0thyj** [comment]
Related to zowe/zowe-cli#744 and should be fixed by https://github.com/zowe/zowe-cli/pull/2167 once it's ported to vNext

**Comment by t1m0thyj** [comment]
Confirmed that this issue is fixed since the Zowe SDKs were updated in https://github.com/zowe/zowe-explorer-vscode/pull/2932
