### ISSUE TITLE
Remove temporary folder setting in vNext

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2951]
Since ZE v3 uses the `FileSystemProvider` and stores files in memory, we should be able to remove the following settings and any code related to the temp folder (creation, cleanup, etc)

![image](https://github.com/zowe/zowe-explorer-vscode/assets/22344007/c8db6f8c-9f8e-48ed-b228-e7487aa4d039)

**Comment by JTonda** [comment]
Document for V3 that temporary folder is no longer used and that extenders should listen for events instead.  Also document how they would access these resources.
