### ISSUE TITLE
Add return types to all interface methods in Zowe Explorer API

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2952]
Zowe Explorer API defines many interfaces containing methods, some of which do not have return types defined.

For example, many of the methods on the `IZoweTree` interface are lacking return types:
https://github.com/zowe/zowe-explorer-vscode/blob/next/packages/zowe-explorer-api/src/tree/IZoweTree.ts

Adding return types could be considered a breaking change but should improve the experience for developers/extenders. For example, when calling `ZoweTreeProvider.addFavorite` it'd be nice to have a return type `Promise<void>` displayed by IntelliSense instead of `any` 😋

**Comment by traeok** [comment]
Something to consider as part of adding return types: do we intend on supporting asynchronous types for some functions? 

For example, the `rename` function could be typed as follows to allow both asynchronous and synchronous operations:
```ts
/**
 * Rename the node. Begins a dialog.
 * @param the node to be renamed
 */
rename(node: IZoweTreeNode): void | PromiseLike<void>;
```
