### ISSUE TITLE
Move sample extensions to separate repo

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2961]
**Is your feature request related to a problem? Please describe.**

The sample extensions may be inconvenient for users to try and for developers to maintain as part of the Zowe Explorer monorepo.

**Describe the solution you'd like**

Move the samples into their own repo, similar to what Microsoft does with https://github.com/microsoft/vscode-extension-samples

**Describe alternatives you've considered**

Leave the samples in the monorepo as they are now, but occasionally this may cause our build workflows to break.

**Additional context**

If we move the samples to a separate repo, we should set up a nightly workflow to ensure they build with the latest ZE API.

**Comment by t1m0thyj** [comment]
Also, the `menu-item-sample` doesn't need to depend on the Zowe Explorer API. It only uses it for the type `IZoweTreeNode`. So either we could make the ZE API a dev dep, or stop using it entirely in favor of `vscode.TreeItem`.

**Comment by JTonda** [comment]
Consider creating a blog on this.
