### ISSUE TITLE
Not able to open HTML file in brwoser directly from Zowe explorer 

### ISSUE THREAD

**Issue by ratnamGT** [zowe/zowe-explorer-vscode#2970]
I have BuildReprt.html file in Mainframe USS which I am opening from Zowe Editor . I am not able to open it in browser directly from here. Could you please suggest how it can be opened in in-built browser in Zowe editor in VS code. Attaching the screenshot.
![Uploading builreport screenshot from zowe editor.png…]()

**Comment by zFernand0** [comment]
Hey @ratnamGT,
It seems like the file was not uploaded properly to the issue. 😢 

Curious if you are using the Z Open Editor or Zowe Explorer.
Either way, which VSCode extension are you using for previewing the HTML file in VSCode?
I'm using `george-alisson.html-preview-vscode` 😋 

![image](https://github.com/zowe/zowe-explorer-vscode/assets/37381190/388668ab-1397-4c9a-823e-28289fb3f81b)

**Comment by ratnamGT** [comment]
Hi @zFernand0  Thanks for your response . I am using Zowe editor to open and preview HTML file.
I have also installed george-alisson.html-preview-vscode extension .
The first issue is ,HTML file is not opening by default in ISO8859-1  encoding ,I need to select encoding each time on HTML file .
second issue is ,it is not previewing and opening the file in VScode browser. It is opening in external brower

**Comment by zFernand0** [comment]
Hey @ratnamGT,
I believe I might be able to help.

> The first issue is ,HTML file is not opening by default in ISO8859-1 encoding ,I need to select encoding each time on HTML file . 

To avoid doing this, you can change the USS File Tag to ISO8859-1.
1. Right-click the `BuildReprt.html` file
2. Select `Edit Attributes`
3. Modify the `Tag` attribute on the displayed form
4. Click on `Apply changes` 

After you have done this, the file should open in ISO8859-1 by default 😋 

> second issue is ,it is not previewing and opening the file in VScode browser. It is opening in external brower

There are a few things that can be causing the HTML file to be opened on a browser by default.
It is possible that some OS configuration might be forcing VSCode to do so.
Another way is based on the keybindings defined in VSCode. For example, 
- `ctrl/cmd + Shift + V` should open in VSCode
- `ctrl/cmd + K` then `W` will open the HTML in a browser.
Please confirm that there aren't any conflicts in the keyboard shorcuts
<img width="370" alt="image" src="https://github.com/zowe/zowe-explorer-vscode/assets/37381190/df41be74-116c-40ba-b465-651aa645a55e">

**Comment by ratnamGT** [comment]
Hi @zFernand0 Thanks for your response ,It resolved the issue

**Comment by zFernand0** [comment]
Hey @ratnamGT,
Thanks for confirming! 🙏🏽 
Closing! 🥳
