### ISSUE TITLE
Rename the Zowe FTP VS Code extension per Linux Foundation trademark guidelines

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-explorer-vscode#2990]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

The extension should be named in a way that complies with the Linux Foundation's trademark usage policy: https://www.linuxfoundation.org/legal/trademark-usage

The specific format for the name should be:
`<your product name> for <The Linux Foundation mark>`

**Describe your enhancement idea**

Change the display name of the `Zowe Explorer Extension for FTP` extension to `FTP for Zowe Explorer`. Also update the name in the first header in the extension's README.md.

**Describe alternatives you've considered**

It could also be changed to `FTP Extension for Zowe Explorer`.

**Provide any additional context**

This is a requirement for Zowe Conformance.

**Comment by JTonda** [comment]
Let's also figure out how to name the CICS extension.
