### ISSUE TITLE
Submit as JCL fails in command palette for USS files

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2991]
**Describe the bug**

When submitting a USS file as JCL, an error is thrown.

**To Reproduce**

Open a USS file that contains JCL and run "Zowe Explorer: Submit as JCL" in the command palette.

**Expected behavior**

Job is submitted successfully.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS 14.5
- Zowe Explorer Version: 2.16.2
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
released with 2.16.3
