### ISSUE TITLE
issue updating credentials in v3 pre-release

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3007]
**Describe the bug**
From user in #zowe-explorer-vscode slack channel:

error message whenever I try to update my credentials. But as soon as I restart my VS Code, it works fine. I am using Zowe Explorer v3.0.0-next.202404242037.

<img width="924" alt="Screenshot 2024-07-17 at 1 45 15 PM" src="https://github.com/user-attachments/assets/050fb687-e525-4634-9e15-2400142ecc98">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: v3.0.0-next.202404242037
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
In addition to the mentioned error message, I'm noticing the same behavior as #2906

**Comment by JillieBeanSim** [comment]
> In addition to the mentioned error message, I'm noticing the same behavior as #2906

Thanks @traeok will add that to the release plan and milestone too 😄

**Comment by t1m0thyj** [comment]
Confirmed that this bug exists in our latest v3 prerelease but is already fixed for the next one by https://github.com/zowe/zowe-explorer-vscode/pull/2956

**Comment by adam-wolfe** [comment]
Addressed in PR #3057
