### ISSUE TITLE
Cancelling Update Credentials removes authentication from profile

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3022]
**Describe the bug**

Cancelling Update Credentials removes authentication from profile, requires VSC refresh to reload full profile

**To Reproduce**

1. Go to manage profile after issuing USS filter search
2. Click on Update Credentials
3. Escape the prompts
4. try to open file or directory
5. see error about missing credentials

**Expected behavior**

profile not altered if canceling Update Credentials

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: 2.17.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by t1m0thyj** [comment]
This should be fixed in https://github.com/zowe/zowe-explorer-vscode/pull/3009/commits/7b161e48861abf34f6c0746b1ceff24dfc3717e2
