### ISSUE TITLE
Items that may need to be ported to `next` 

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3095]
Some items that may still need porting to the next branch before it becomes our main branch:

- [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/3090~
  - port PR: #3097 
- [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/3064~
  - port PR: #3104
- [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/3075~
  - port PR: #3105
- [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/3092~
  - This one does not need to be ported as [the range of SDK versions (`>=8.0.0-next.0 <8.0.0`)](https://github.com/zowe/zowe-explorer-vscode/blob/next/samples/uss-profile-sample/package.json#L49-L50) already covers the micromatch transitive dependency from the CLI.
  - However, we could update our [devDependency `packages/zowe-explorer > expect^24.9.0`](https://github.com/zowe/zowe-explorer-vscode/blob/next/packages/zowe-explorer/package.json#L1837) which has `micromatch: 3.1.10` as a (2nd level) transitive dependency. 
    - Personal vote: Let's hold off on it since it's just a devDep 😋 
- [x] ~https://github.com/zowe/zowe-explorer-vscode/pull/3017~
  - port PR: #3096 
- [x] https://github.com/zowe/zowe-explorer-vscode/pull/3107 @JillieBeanSim 
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/2749 @SanthoshiBoyina1
- [x] https://github.com/zowe/zowe-explorer-vscode/pull/2766 @t1m0thyj 
  - port PR: #3135
- [x] https://github.com/zowe/zowe-explorer-vscode/pull/2767 @t1m0thyj 
  - port PR: #3135
- [x] https://github.com/zowe/zowe-explorer-vscode/pull/2768 @likhithanimma1 
- [x] https://github.com/zowe/zowe-explorer-vscode/pull/2807 @t1m0thyj 
  - port PR: #3135
- [x] https://github.com/zowe/zowe-explorer-vscode/pull/2882 @t1m0thyj 
  - port PR: #3135
  - Note: Most of this PR didn't need to be ported because FSProvider auto-detects binary content in files 😋 

Also, I updated all missed CHANGELOG updates in [PR](https://github.com/zowe/zowe-explorer-vscode/pull/3094/files) for v3 pre-release.  Some of these items being added to CHANGELOG may need rechecking for verification of porting.

**Comment by t1m0thyj** [comment]
> Also, I updated all missed CHANGELOG updates in [PR](https://github.com/zowe/zowe-explorer-vscode/pull/3094/files) for v3 pre-release. Some of these items being added to CHANGELOG may need rechecking for verification of porting.

Reviewed the list of changelog updates and found several PRs that may need to be ported so I've added them above.

**Comment by JillieBeanSim** [comment]
FYI @SanthoshiBoyina1 & @likhithanimma1

**Comment by JillieBeanSim** [comment]
my port is not a port but a different solution and PR is up https://github.com/zowe/zowe-explorer-vscode/pull/3140

**Comment by SanthoshiBoyina1** [comment]
PR #3144 to port Incorrect job label under favorites #2749 to v3

**Comment by likhithanimma1** [comment]
PR #3145 to port Sort Jobs by timestamp #2768 to v3

**Comment by JillieBeanSim** [comment]
closing, all items have been ported. Thanks all!
