### ISSUE TITLE
Zowe Resources tab open empty on startup

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3113]
**Describe the bug**

Zowe Resources tab open empty on startup

<img width="574" alt="Screenshot 2024-09-17 at 10 40 33 AM" src="https://github.com/user-attachments/assets/7a9a81d5-3482-485f-9e25-db4cb37055fe">

**To Reproduce**

1. start VS Code with latest ZE v3 pre-release
2. Open or look in the terminal area of VS Code
4. See tab available with no information or a way to interact with it

**Expected behavior**

Window should not open on startup or window should open on startup with a way to interact with it.

**Desktop (please complete the following information):**

- OS: macos
- Zowe Explorer Version: latest v3-prerelease
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
Hi @JillieBeanSim, this is by design. We still have to keep that panel visible in this section, even if we aren't showing content, so I'm not sure what actions we can take here.

**Comment by traeok** [comment]
@JillieBeanSim, sorry for the confusion as I had misspoke earlier. I was under the impression that we could not hide the panel but this is not the case if we use a custom context value. I've created PR to hide the panel until it is used by another feature/action: https://github.com/zowe/zowe-explorer-vscode/pull/3115

Thanks for the suggestion!

**Comment by JillieBeanSim** [comment]
closing, issue resolved with PR #3115
