### ISSUE TITLE
v3 - Unable to open sequential data sets or members with an RSE profile

### ISSUE THREAD

**Issue by benjamin-t-santos** [zowe/zowe-explorer-vscode#3117]
**Describe the bug**

When I try and open a sequential data set or data set member in the Data Sets view, the file never successfully opens in the editor.
The error: `Error: EROFS: read-only file system, mkdir '/user/'` is logged to the console.

**To Reproduce**

1. Create an RSE profile
2. Search for data sets with a filter
3. Try and open a sequential data set or PDS member

**Expected behavior**

The selected resource should open in the editor

**Screenshots**

https://github.com/user-attachments/assets/96ba6bc8-00a9-4fd8-92e6-67a5c24e09bf

**Desktop (please complete the following information):**

- OS: macOS Sonoma
- Zowe Explorer Version: [v3.0.0-next.202409132122](https://github.com/zowe/zowe-explorer-vscode/releases/tag/v3.0.0-next.202409132122)
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
Hi @benjamin-t-santos,

Have you been able to reproduce this issue when using a z/OSMF profile? 

I noticed that the error mentions `ibm.zopeneditor.4.4.0/.../extension.js` in the stack trace and has `[IBM.zopeneditor]` before the first error message. If the error is specific to RSE profiles, the issue may need moved to IBM/zopeneditor-about.

Thanks

**Comment by benjamin-t-santos** [comment]
That is a very good point - I don't see it in z/OSMF profiles, so I will close it here and move it there.
