### ISSUE TITLE
Zowe Explorer v3 does not refresh profiles on password change

### ISSUE THREAD

**Issue by phaumer** [zowe/zowe-explorer-vscode#3120]
**Describe the bug**

**To Reproduce**

I built Zowe Explorer from source on 9/16. Installed on Windows test machine where stored password was expired. After changing password in prompt I could run a query to see my data sets, but when opening a file from a PDS member I get a 401. 

**Expected behavior**

**Screenshots**

<img width="525" alt="image" src="https://github.com/user-attachments/assets/27aec5e0-1bd7-4ad0-9202-003cbd71ef0d">

**Desktop (please complete the following information):**

- OS: Win 11
- Zowe Explorer Version: v3, 9/16
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store? yes

**Additional context**

**Comment by traeok** [comment]
I believe this PR is related and should resolve the issue: https://github.com/zowe/zowe-explorer-vscode/pull/3111
