### ISSUE TITLE
Convert from v1 to team config misbehavior across workspaces

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3123]
**Describe the bug**

The prompt that v1 profiles are present and to convert to v2 always appears on every workbench startup, even though I do not have any v1 profiles present. Pressing "Convert Existing Profiles" fails and issues an error message

On VsCode startup having ZE v3 installed, my workbench always seems to reload at least once. Maybe due to this.

v3.0.0-next.202409091409

split from https://github.com/zowe/zowe-explorer-vscode/issues/3089#issuecomment-2347244119

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
testing the latest release https://github.com/zowe/zowe-explorer-vscode/releases/tag/v3.0.0-next.202409132122
if no v1 profiles found no convert prompt was given.
with v1 profiles found I was prompted to convert and after converting the `profiles` folder is renamed to `profiles-old` which should result in v1 profiles not being found after the conversion.
v1 profiles were only available as a global option and the check/option to convert happens during activation.
If I cancel the prompt in one VSC window and do not create any profiles/team config and open another VSC window I will see the prompt again.  This is working by design, each VSC instance goes through activation and ZE checks for the existence of v1 profiles offering the user a way to continue to use these profiles or create new.

**Comment by traeok** [comment]
I'm noticing the same behavior:

- When no v1 profiles are found, the prompt isn't shown
- With v1 profiles, the prompt appears and after selecting "Convert Existing Profiles", the prompt disappears and my profiles are converted. After reloading the window the prompt does not appear again
- Clicking "Cancel" will dismiss the prompt, and if I do nothing and open another VS Code window, the prompt appears again (expected)
