### ISSUE TITLE
Unable To Copy and Paste Files/Directories on USS for Zowe Explorer 3.0.0

### ISSUE THREAD

**Issue by jackyhodev** [zowe/zowe-explorer-vscode#3128]
**Describe the bug**
I am unable to copy and paste Files and Directories on USS for Zowe Explorer 3.0.0 for both zOSMF and RSE profiles. I am getting an error: `Error uploading files TypeError: t.tree.localUri.with is not a function`

**To Reproduce**

1. Install Zowe Explorer 3.0.0 on VSCode
2. Open USS 
3. Select a zOSMF or RSE profile
4. Right click on any file/directory
5. Select Copy
6. Right click on any directory or the root folder
7. Select Paste

**Expected behavior**
File/Directory is not pasted successfully and you get a notification like the screenshot below:

**Screenshots**
<img width="461" alt="image" src="https://github.com/user-attachments/assets/bf2c378e-77f1-4186-9902-b4b1c9b3b03e">

**Desktop (please complete the following information):**

- OS: MacOS and Windows
- Zowe Explorer Version: 3.0.0

**Additional context**

**Comment by traeok** [comment]
Hi @jackyhodev, thanks for reporting this. I've implemented a fix as part of #3127

**Comment by jackyhodev** [comment]
Thank you! @traeok
