### ISSUE TITLE
zowe explorer defaults to https despite having set http in profile

### ISSUE THREAD

**Issue by Madhubalan-p** [zowe/zowe-explorer-vscode#3156]
**Describe the bug**
I am connecting to rseapi thru zowe explorer using HTTP protocol which is is not working. same is working fine in ZOWE CLI. on the zOS host side, rseapi is not configured to be run as HTTPS.

**Steps to Reproduce**

1. connect to rseapi using http in zowe explorer

**Expected behavior**
connection to rseapi from zowe explorer must work

**Screenshots**
getting htt event error where the log says http.

**Logs**
If applicable, add server logs collected at the time of your problem.

**Details**
 - Zowe explorer 2.18, zowe cli 7.29 
 - Test environment: zD&T

**Comment by JillieBeanSim** [comment]
Hello @Madhubalan-p there is a known issue [documented](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#http-protocol-support-for-rse-profiles) for the Zowe RSE connection protocols.  Can follow the documentation and issue linked for updates regarding the RSE profile type connection.  Thanks
