### ISSUE TITLE
Encoding not honored for spool files

### ISSUE THREAD

**Issue by VitGottwald** [zowe/zowe-explorer-vscode#3172]
**Describe the bug**

When I specify `encoding` in my z/OSMF profile it is honored for dataset retrieval/upload but not for spool file retrieval.

This is most likely because the following call does not take encoding into account https://github.com/zowe/zowe-explorer-vscode/blob/b43eccb8c6a0ac35b0cd6282d27afc65f7f9f3f7/packages/zowe-explorer/src/trees/job/JobActions.ts#L177 

**To Reproduce**

1. Set `encoding` in zosmf profle to `ibm278`
1. Create a PDS member containing a nordic national character like `Ö`
1. Print it to spool - e.g. via IEBGENER
2. Open the PDS member and see `Ö`
3. Open the spool file and see `@`

**Expected behavior**
Encoding from zosmf profile is honored both for dataset and spool operations.

**Comment by VitGottwald** [comment]
The situation that I ran into this was when looking at a listing of a COBOL program that uses a nordic encoding.

**Comment by JTonda** [comment]
Closing in favor of #1941
