### ISSUE TITLE
Multiple problems after push of 10.2 and plugin refresh

### ISSUE THREAD

**Issue by johntgatesjr** [zowe/zowe-explorer-vscode#3184]
**Describe the bug**
A clear and concise description of what the bug or error is.

**Steps to Reproduce**

1. Connect to z/OS machine and open an existing Assembler PDS member.
2.

**Expected behavior**
- All formatting lost on assembler macro libraries.
- Output view will not populate.    {No symbols found in document PTYPLST.asm}
- Find options on Edit pull down does not function correctly.  Highlighted field in source is ignored and a search window is opened instead.

**Details**

Mac/OS. 14.7

VS Code.
Version: 1.94.0 (Universal)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Zowe plugin.
Published
2018-08-29, 14:33:40
Last released
2024-10-01, 16:56:37
Last updated
2024-10-02, 12:49:49
Identifier
zowe.vscode-extension-for-zowe

**Additional context**
This is a sev 1 issue for us as this push has rendered key functions of the Zowe plugin unusable and left it completely broken with no ability to roll back the push of the 10/2 update.

**Comment by traeok** [comment]
Hi @johntgatesjr,

If I understand this correctly, it sounds like this could be related to issue #3181? If you have existing file associations for data sets, you may need to update them to handle PDS members. In [this issue comment](https://github.com/zowe/zowe-explorer-vscode/issues/3181#issuecomment-2393608608), I included some examples of file associations that will handle the new path structure.

**Comment by johntgatesjr** [comment]
I don’t believe this is the problem I am seeing, particularly for the complete withdrawal of useful Find support.  This push seems to have completely changed (removed) useful support for Finding and displaying information within a file.  It also does not explain why the Outline function doesn’t work at all.

As far as changing file structures, I did get a message after starting 10.2 for the first time that you were changing my connection profiles.  There were no flags and/or warnings about what or how these changes might impact existing function.  There were no warnings about internal path changes or file association required changes.  If you made changes that required changes on my part, you didn’t do a complete migration.    If you’ve introduced a change that breaks functionality, I consider this an incompatible change.

Some additional comments:

  1.  Incompatible changes are bad and you should never do it.
  2.  See Comment 1.  If you choose to violate comment 1, you better have a very good reason to do it and you must pre-announce the changes and/or actions required to mitigate those changes.
  3.  If you change something that removes or changes existing functionality, you need to clearly point this out before you migrate anything.

If the changes made in 10.2 are not addressed, we will likely abandon Zowe as we consider it unusable without those functions.


[A picture containing font, graphics, graphic design, screenshot  Description automatically generated]
Empowering businesses with SECURE DATA


John Gates | Principal Mainframe Architect Engineer


From: Trae Yelovich ***@***.***>
Date: Friday, October 4, 2024 at 9:37 AM
To: zowe/zowe-explorer-vscode ***@***.***>
Cc: John Gates ***@***.***>, Mention ***@***.***>
Subject: [Ext] Re: [zowe/zowe-explorer-vscode] Multiple problems after push of 10.2 and plugin refresh (Issue #3184)
NOTIFICATION: External Email

Hi @johntgatesjr<https://github.com/johntgatesjr>,

If I understand this correctly, it sounds like this could be related to issue #3181<https://github.com/zowe/zowe-explorer-vscode/issues/3181>? If you have existing file associations for data sets, you may need to update them to handle PDS members. In this issue comment<https://github.com/zowe/zowe-explorer-vscode/issues/3181#issuecomment-2393608608>, I included some examples of file associations that will handle the new path structure.

**Comment by t1m0thyj** [comment]
@johntgatesjr I agree that incompatible changes are bad and we would like to assist you to resolve the issues that you’re seeing. Some of the features you mentioned such as Find support and Outline function for Assembler are not included in Zowe Explorer itself. In order for us to reproduce the issue, could you please provide a list of all the mainframe-related extensions you have installed in VS Code?

**Comment by johntgatesjr** [comment]
Thanks, Tim.   Pretty simple environment.

Zowe Explorer                                                  v.2.18.0               Rolled back from v.3.1.0
C/C++                                                                  v.1.21.6
C/C++ Extension Pack                                 v.1.3.0
C/C++ Themes                                                 v.2.0.0
CMake                                                                 v.0.0.17
CMake Tools                                                     v.1.19.52
Gitlens                                                                 v.15.5.1
IBMZ Open Debug                                          v.4.3.1                  Not currently in use
IBMZ Open Debug Profiles view               v.3.1.2                  Not currently in use
IBM Z Open Editor                                          v.4.5.1
Vim                                                                        v.1.28.1


The problems are easy to reproduce.

On 2.18:

  1.  Open an ASM part.
  2.  Highlight field.
  3.  Right click.
  4.  Dropdown including Find All References
  5.  VS Code Edit dropdown
  6.  Selections including Find, Replace, Find in Files,  Replace in Files.
  7.  Selection of any of the above results in a search window populated with search results of highlighted field.
  8.  Outline pane open.
  9.  Pane populates when part is opened.  Pane updates as fields are selected.

On 3.1:

  1.  Open an ASM part.
  2.  Highlight field.
  3.  Right click.
  4.  Crickets.  Nothing happens.  No dropdown.
  5.  VS Code Edit dropdown
  6.  Selections including Find, Replace.  Find selection opens empty search box with nothing populated.
  7.  Outline pane open.
  8.  Pane does not populate when part is opened.


[A picture containing font, graphics, graphic design, screenshot  Description automatically generated]
Empowering businesses with SECURE DATA


John Gates | Principal Mainframe Architect Engineer


From: Timothy Johnson ***@***.***>
Date: Friday, October 4, 2024 at 12:07 PM
To: zowe/zowe-explorer-vscode ***@***.***>
Cc: John Gates ***@***.***>, Mention ***@***.***>
Subject: [Ext] Re: [zowe/zowe-explorer-vscode] Multiple problems after push of 10.2 and plugin refresh (Issue #3184)
NOTIFICATION: External Email

@johntgatesjr<https://github.com/johntgatesjr> I agree that incompatible changes are bad and we would like to assist you to resolve the issues that you’re seeing. Some of the features you mentioned such as Find support and Outline function for Assembler are not included in Zowe Explorer itself. In order for us to reproduce the issue, could you please provide a list of all the mainframe-related extensions you have installed in VS Code?

**Comment by phaumer** [comment]
Hello @johntgatesjr. Z Open Editor 4.5.1 and Zowe Explorer 3.0 can not work together. There should have been an error dialog to warn you: `"Zowe Explorer VS Code Extension 3.0.0 is not compatible. Update Zowe Explorer to a 2.x version."`

You can can back to 2.18 by selecting the version to install and preventing updates. See here for more details:

- <https://github.com/IBM/zopeneditor-about/discussions/435>
- <https://github.com/IBM/zopeneditor-about/issues/448>

**Comment by johntgatesjr** [comment]
Peter,
You and I have gone back and forth on this issue many times before.  I don't need another explanation.  What I need from IBM is a solution that works.  I believe what you're telling me is the latest level of Zowe and the latest level of Z Open Editor do not in fact work together.  If this is true, disappointment does not adequately describe my feelings about the lack of planning on IBM's part to provide a solution that works.  I have already rolled back Zowe to 2.18 and regained my lost function.  At the same time, I am recommending to my organization that search for another vendor solution.  We simply cannot continue to expose our developers to this sort of thing.

**Comment by phaumer** [comment]
We do provide a consistent set of components that work together and were tested together on our Mainframe Download Site here: https://ibm.github.io/mainframe-downloads/downloads.html. 

Zowe is just an open-source project and provides releases when they are ready. Zowe 2 was delayed for weeks messing with our release plans at the time and even this release was announced for the 28th, then the 30th and it the only shipped on the 1st. Our [alpha version of Z Open Editor](https://github.com/IBM/zopeneditor-about/releases/tag/5.0.0-alpha1) was actually provided on time on the 30th when the Zowe people were still voting and discussing. No one can plan for this.
