### ISSUE TITLE
Element with id No jobs found is already registered

### ISSUE THREAD

**Issue by SanthoshiBoyina1** [zowe/zowe-explorer-vscode#3201]
**Describe the bug**

Seeing an additional error message `Element with id No jobs found is already registered`, When an invalid jobid(that doesn't exists) is used with `Search by job ID` option in the Jobs Tree with two different profiles. 

**To Reproduce**

**Expected behavior**

To avoid seeing the error message `Element with id No jobs found is already registered`

**Screenshots**

<img width="1454" alt="Screenshot 2024-10-09 at 11 49 36 AM" src="https://github.com/user-attachments/assets/68817ad3-2eed-4b27-8b0c-c28c27e7df82">

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: V3.0.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by SanthoshiBoyina1** [comment]
> @SanthoshiBoyina1 I see the same error in 3.0.0, but it seems fixed in 3.0.1. Could you test the VSIX from the 3.0.1 PR? #3202

Tested this issue with 3.0.1 and 3.0.1. It is working fine without popping up the error message.

**Comment by t1m0thyj** [comment]
@SanthoshiBoyina1 Can this issue be closed?

**Comment by SanthoshiBoyina1** [comment]
Yes @t1m0thyj , It can be closed.
