### ISSUE TITLE
When launching Zowe Explorer in debug, it is prompting me to disable the default credential manager

### ISSUE THREAD

**Issue by KaranP25** [zowe/zowe-explorer-vscode#3244]
**Describe the bug**

When I try to launch Zowe Explorer in debug mode, it will show the following error:

![image](https://github.com/user-attachments/assets/24d733eb-3a36-4075-b94e-4519c223c037)

It results in not opening any profiles if you do disable it.

<img width="471" alt="image" src="https://github.com/user-attachments/assets/f5de5408-1083-440e-a305-43b3e37a70bd">

**To Reproduce**

1. Launch Zowe Explorer in debug mode
2. You will see the above prompt

**Expected behavior**

It should not prompt this and use the default credential manager.

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: 3.0.1 (Latest pull from the main branch)
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Comment by traeok** [comment]
Hi @KaranP25,

After running `pnpm install` and `pnpm build` from the root of the repository, is there a `prebuilds` folder present within the `packages/zowe-explorer` folder? This folder should contain the prebuilds for the Secrets SDK, which is needed to initialize the credential manager.

**Comment by KaranP25** [comment]
Hi @traeok, yea it does now. I just had to downgrade my node to v20.11.0 from v20.16.0. And reinstalled pnpm to v8.15.9 from the latest version. Before that there were a bunch of errors after running the build command. Thanks it works now.

**Comment by KaranP25** [comment]
Seeing this error after trying to login with token based auth. Similar error to earlier prompt as above. Do I need to enable anything after the build?

![image](https://github.com/user-attachments/assets/5c885fdf-a38c-49e3-acc9-1588bd6e28df)
