### ISSUE TITLE
Add "Add to Workspace" to context menu for data sets and USS directories

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#3265]
**Is your feature request related to a problem? Please describe.**

I want a way to easily add a data set or USS folder as a virtual folder to my VS Code workspace.

**Describe the solution you'd like**

It would be convenient if the Data Sets and USS trees had an "Add to Workspace" item in the right-click menu.

Also our documentation should mention the virtual workspace support introduced in Zowe Explorer V3.

**Describe alternatives you've considered**

Users can run the command `Workspaces: Open Workspace Configuration File` and manually add a `zowe-ds:` or `zowe-uss:` link to their list of workspace folders.

**Additional context**

Consider where this context menu item should be shown - probably at least for PDS data sets and USS directories, and maybe also for data set patterns, sequential data sets, and USS files?

**Comment by traeok** [comment]
Working on this as part of innovation work for enhancing the virtual workspace experience 😋
