### ISSUE TITLE
401 after refreshing APIML token when trying to view job spool

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-explorer-vscode#3289]
**Describe the bug**

If I have an expired token, reauthenticate, list jobs, then try to view the spool files, I get an error 401. This behaves similarly to https://github.com/zowe/zowe-explorer-vscode/issues/3150, except with viewing job spool rather than members.

**To Reproduce**

1. Start VS Code with an expired APIML token.
2. Try to list data sets and get prompted to refresh your token.
3. Refresh your token by reauthenticating.
4. List jobs by user ID
5. Expand a job and click on a spool file
6. Get an error 401

Not sure if it's relevant, but I am using nested profiles for APIML connections.

**Expected behavior**

The new token should be used when trying to download spool files.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: built from main as of https://github.com/zowe/zowe-explorer-vscode/commit/dbce3885751b20e2b43f587d34d9a58cb9bf0903
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JTonda** [comment]
#3243

**Comment by traeok** [comment]
> #3243 - This PR should improve the experience of getting a 401 error when opening a file in the editor.

Update - sorry for the confusion, but this PR will not improve this behavior as we have outstanding bugs with the credential prompt that need resolved. Once those are fixed, users can update credentials through the Manage Profile menu. The "Try again" button will work as expected in the editor, using the new creds.

We cannot prompt the users from the provider to enter in credentials as this would be a breaking change for extenders calling `readFile`.
