### ISSUE TITLE
New Install of 3.0.2 - Extension wouldn't activate

### ISSUE THREAD

**Issue by baldben1** [zowe/zowe-explorer-vscode#3290]
**Describe the bug**
On install of 3.0.2 with no previous profiles, extension fails to activate or results in 'Error running command zowe.uss.addSession' after prompt for new profile or profile conversion. (MacOS)

**To Reproduce**
Install Zowe fresh with no profiles established.
Click 'new' or 'convert' at prompt.
Based on selection, clicking '+' will result in extension not loading or 'Error running command zowe.uss.addSession' 
Had to install previous version, 3.0.1, then '+' worked as expected. After profile established, I was able to upgrade to 3.0.2 without apparent issue.

**Expected behavior**
'+' button should allow new profile

**Screenshots**

**Desktop (please complete the following information):**

- OS:MacOS
- Zowe Explorer Version:3.0.2
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by t1m0thyj** [comment]
This may be related to #3273

**Comment by JillieBeanSim** [comment]
this is fixed in the 3.0.3 preparation [PR](https://github.com/zowe/zowe-explorer-vscode/pull/3301)

**Comment by JillieBeanSim** [comment]
Hey @baldben1 was this issue resolved for you with Zowe Explorer 3.0.3?

**Comment by baldben1** [comment]
I did the work around I mentioned earlier and was able to use it since
then. I don't want to lose my stuff I've done since, but if it's as simple
as uninstalling and reinstalling the extension I can test it.

**Comment by traeok** [comment]
**v3.0.3**: In a fresh environment (Windows Sandbox) with no profiles in place, I do not see the profiles conversion prompt as mentioned in the original post. Instead I see a "No configs detected" message in the bottom right corner:

![image](https://github.com/user-attachments/assets/27838f81-892f-4688-a6ca-c7f8182fd870)

Clicking "Create New" presents a quick pick at the top where the user can select "+ Create a new Team Configuration file". After clicking this option the config appears in the editor and the profile is added to my tree. I can continue to use Zowe Explorer as expected and no activation errors are present.
