### ISSUE TITLE
Renaming a PDS does not update member nodes

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#3314]
**Describe the bug**

When I rename a PDS in Zowe Explorer, then opening its members fails because their resource URI is not updated.

**To Reproduce**

* Search for a dataset pattern that matches a PDS
* Expand the PDS node to reveal members
* Right-click the PDS node and select the Rename option
* After renaming the PDS, click on one of its members
* Notice the member fails to open because URI is outdated

**Expected behavior**

The resource URI stored on the member nodes should be updated when the PDS is renamed.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
This seems to only affect a PDS that's already expanded or has members open in the editor - that said, it was a quick fix so I put up a [PR](#3315)
