### ISSUE TITLE
ze(uss): `Pulling from mainframe` status bar message does not get disposed of for binary files

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#3355]
**Describe the bug**

The status bar message doesn't go away when you open a USS file as binary and then pull from mainframe
![image](https://github.com/user-attachments/assets/6f2cc592-ddad-46c0-90b6-c29b7c5b2f4e)

**To Reproduce**

1. Open a USS file as binary (via the open with encoding option)
2. Right click on the same file and `Pull from mainframe`
3. Notice the status bar message not getting disposed of.
![image](https://github.com/user-attachments/assets/ad21a335-c145-45cb-8334-6673136d0c70)

**Expected behavior**

For the message to go away eventually 😋 

**Screenshots**

![image](https://github.com/user-attachments/assets/64515343-ff8a-40bd-9e81-d7ac99a0525b)

**Desktop (please complete the following information):**

- OS: All
- Zowe Explorer Version: 3.0.3
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

Found while looking for a Download option for USS files and Dataset.
Thanks @roman-kupriyanov

---

Since the node's contextValue is `binaryFile`, the `SharedContext.isDocument()` doesn't consider it as a valid document. Thus we remove it from the list.
![image](https://github.com/user-attachments/assets/b522abda-2265-43e1-adef-875296b79519)

I think we just need to dispose of the status message outside the for-loop
![image](https://github.com/user-attachments/assets/8b284999-3fd5-474c-bb27-054a2ea412fe)

**Comment by traeok** [comment]
Keeping open until ported to v2
