### ISSUE TITLE
Move away from Codecov and implement Sonar Cloud

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#473]
This should alleviate the burden of having to increase coverage on unrelated code since Codecov usually got confused between target branches.
Examples of sonar cloud usage are Zowe Imperative and Zowe CLI

**Comment by VitGottwald** [comment]
@zFernand0 what is the benefit of sonar cloud? My experience with sonar is that it cannot be run on developers machine and significantly increases development feedback time.

**Comment by zFernand0** [comment]
> what is the benefit of sonar cloud? My experience with sonar is that it cannot be run on developers machines and significantly increases development feedback time.

Hey @VitGottwald, Apologies for not replying any sooner. I hope that the conversation during today's call was able to resolve some of the concerns regarding the feedback time.
As said on the call, we will be sharing the the contents of the webinar as soon as we can. 
CC'ing @MikeBauerCA

**Comment by MikeBauerCA** [comment]
@VitGottwald @zFernand0 @crawr @jellypuno you can register and view the webinar at https://webinars.devops.com/a-zowe-cli-enabled-roadmap

The demo is focused on incorporating code quality tools like SonarQube into CI/CD pipelines for mainframe apps. It shows the value of SonarCloud and how to run the scan from the developer's machine using the Sonar Scanner CLI.

**Comment by VitGottwald** [comment]
Thank you for the answer @zFernand0! I have one more question. 

Is the sonar cloud configuration - the definition of linting rules, thresholds, etc. - stored in the form of a config file in the repo? Or is it stored on the in sonarcloud?

**Comment by zFernand0** [comment]
We will be discussing more on this in the `#zowe-explorer` [OMP slack](https://slack.openmainframeproject.org/) channel.

The short answer is yes, it's possible to configure SonarCloud from either the server or the repository. : )

**Comment by VitGottwald** [comment]
I should have really asked this as the very first question. Can someone point me to an example of where Codecov was broken?

**Comment by zFernand0** [comment]
Hey @VitGottwald, Here is a reference to the issue in codecov. https://github.com/codecov/codecov-bash/issues/83
In [this comment](https://github.com/zowe/vscode-extension-for-zowe/pull/296#issuecomment-552892394) you can find an example of one of the problems this issue causes.

**Comment by VitGottwald** [comment]
The report of the issue https://github.com/codecov/codecov-bash/issues/83 says that a rebase on master resolves the problem. Did we try that in the cases we had a problem?

**Comment by VitGottwald** [comment]
oops, clicked on wrong button, sorry

**Comment by zFernand0** [comment]
> The report of the issue [codecov/codecov-bash#83](https://github.com/codecov/codecov-bash/issues/83) says that a rebase on master resolves the problem. Did we try that in the cases we had a problem?

If I remember correctly we have done it in the past, and the issue seemed to go away, but becuase of the branch protection rules, we soon find ourselves in a similar situation as before.
![image](https://user-images.githubusercontent.com/37381190/78674256-504d2900-78b1-11ea-94f8-491beb2e690d.png)

**Comment by VitGottwald** [comment]
I did a small research today. All of the open source projects I could come up with either do not use code coverage within their pull requests at all or use Codecov. I wonder why it is not an issue for them but it is here. I wish I had such a broken branch to play with it.

**Comment by JillieBeanSim** [comment]
closing now that we have Sonar Cloud working

**Comment by t1m0thyj** [comment]
Re-opening since we are still using Codecov to report on patch/project coverage, and SonarCloud is not reporting coverage info.

In the future, we should investigate migrating to SonarCloud for reporting coverage info on PRs and in the readme badge.
