### ISSUE TITLE
Move from Zanata to POEditor

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#546]
As a developer, I'd like to have a way to easily translate the Zowe Explorer from an intuitive website and have the translation files automatically updated thanks to the [integration features](https://poeditor.com/kb/localization-file-management-with-github-bitbucket-and-gitlab-integrations) provided by the tool.

I believe we can continue to use the same setup that we have today to compile the translatable text. It'd be a matter of integrating POEditor and configuring its permissions.

**Comment by t1m0thyj** [comment]
Zanata is in the process of being sunset and will be permanently shut down on 2024-09-09: https://lists.osci.io/hyperkitty/list/zanata-sunset@lists.osci.io/message/6F2D6JRPFF6RRKYURB2WMCXSJ6C4AFBS/

This may increase the priority for us to migrate to an alternative platform like POEditor for managing translations 😋
