### ISSUE TITLE
Automate updating of i18n samples

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-explorer-vscode#677]
Enforce that the i18n samples generated by "scripts/stringUpdateScript.js" stay up to date.

Some things that could be done to help with this:
* Run the NPM update script as a postbuild task
* Fail the PR build in Jenkins if the i18n samples directory is out of date

**Comment by t1m0thyj** [comment]
For Zowe Explorer v3 we have migrated to the `vscode-l10n` package and the i18n samples directory no longer exists 😋
